### ISSUE TITLE
Decimal parsing format depends of OS regional settings

### ISSUE THREAD

**Issue by iamhere2** [mganss/XmlSchemaClassGenerator#101]
Hello!  I have a problem with the way xscgen parse decimal numbers.

Try to parse xsd with decimal attribute and default value:
`<xs:attribute name="SomeAttr" type="xs:decimal" default="1.5">`

If your OS settings set up to use comma (',') as decimal separator, you will receive an error from xscgen:

```
Unhandled Exception: System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(ReadOnlySpan`1 str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDecimal(String value, IFormatProvider provider)
...
```

XSD standard requres period as decimal separator:
> decimal has a lexical representation consisting of a finite-length sequence of decimal digits (#x30-#x39) separated by a period as a decimal indicator. An optional leading sign is allowed. If the sign is omitted, "+" is assumed. Leading and trailing zeroes are optional. If the fractional part is zero, the period and following zero(es) can be omitted. For example: -1.23, 12678967.543233, +100000.00, 210.

https://www.w3.org/TR/xmlschema-2/#decimal-lexical-representation

I think, XmlSchemaClassGenerator should use own fixed format for parsing instead of deafult, which uses OS locale/Culture settings.

**Comment by mganss** [comment]
Whoopsie 😊 Should be fixed now, though in my testing I saw that a default of "1.5" was parsed as 15 (this was with a de-DE culture).

**Comment by dmitry-ra** [comment]
@iamhere2, hello from the Modeus of the future, where I spent a few hours to debug XSD generator crash in GenerateSchemaClasses.ps1. Meet here was our destiny :)

**Comment by mganss** [comment]
@dmitry-ra Does this issue still occur with the current version?

**Comment by dmitry-ra** [comment]
@mganss, all ok, sorry for offtopic. Thank you for this tool!
