### ISSUE TITLE
Assigning collections

### ISSUE THREAD

**Issue by iamhere2** [mganss/XmlSchemaClassGenerator#102]
Hello again!
Xscgen is a nice tool, but I have some ideas to improve it.

Sometimes it's very handy to create xml document object model as a one large expression, for example:
```
            var doc = new Schema.Document
            {
                Name = ...,
                Plan = new Schema.Plan
                {
                    Code = ...,
                    Title = new Schema.Title
                    {
                    ...
```
And it would be more convenient, if I could assign a collection properties, but I can't now, because collection properies has only getter public, not setter :(

Standard .NET Framework's xsd.exe generates code, that allow such expressions:
 
```
            var doc = new Schema.Document
            {
                Name = ...,
                Plan = new Schema.Plan
                {
                    Code = ...,
                    Title = new Schema.Title
                    {
                       // PlanRows is a collection property here 
                       PlanRows = myPlan.Select((r, i) => 
                               new Schema.PlanRow
                               {
                                   Num = i + 1,
                                   Name = r.Name,
                                   ... 
                               }
                        ).ToArray()
```
Xscgen could generate a setter for collection properties (of type `ICollection<T>` initialized as `Collection <T>`), which copies all items of `value` (of type `ICollection<T>`) to the backing field collection.

I think, this capability can be optional, with turning on/off via a comand line args.

**Comment by mganss** [comment]
Collection initializers can use extension methods:

```C#
static class Extensions
{
    internal static void Add<T>(this List<T> l, IEnumerable<T> l2)
    {
        l.AddRange(l2);
    }
}
```

and then:

```C#
PlanRows = { myPlan.Select(...) }
```

**Comment by iamhere2** [comment]
Oh, I missed it :)

**Comment by mganss** [comment]
No problem, thanks for your feedback.
