### ISSUE TITLE
No class generated

### ISSUE THREAD

**Issue by PedroS11** [mganss/XmlSchemaClassGenerator#108]
I tried running the .exe to generate the class, however no file was created. No error was displayed too. Any idea what can be wrong?

[ND-Message-1.0.xsd.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/3004722/ND-Message-1.0.xsd.zip)

> Command
 C:\Users\pedro.silva\Downloads\XmlSchemaClassGenerator.2.0.230\XmlSchemaClassGene
rator.Console.exe .\ND-Message-1.0.xsd -p=TEU

**Comment by PedroS11** [comment]
I managed to fix it.

1- dotnet tool install --global dotnet-xscgen --version 2.0.230	
2- xscgen ND-Message-1.0.xsd -p=TEU

However, it generates a file with errors

**Comment by mganss** [comment]
What kind of errors do you get?
Can you include `../common/ND-BaseMessageComponents-1.0.xsd` in the zip?

**Comment by PedroS11** [comment]
It's already fixed, I didn't use all the types necessary, my fault. Thank you anyway :D
