### ISSUE TITLE
No interface generated for <xs:group/> elements...

### ISSUE THREAD

**Issue by borzag** [mganss/XmlSchemaClassGenerator#109]
Hi, 

First of all, thanks a lot for developing and sharing this godsend tool! It's really amazing and simplifies things a lot!

As I have read in the documentation for the tool, it shall be possible to get interfaces generated for ```<xs:group/>``` elements by default, but i can't get it to work for me. Adding a ```<xs:attributegroup/>``` does the work flawlessly and generates a interface for the members of the attributegroup. 

I have a main xsd file that defines all the elements and types that i'm using. In this file i have also created a ```<xs:group name="DefaultData">``` in which i have included a subset of the elements. I have two other XSD files that includes the main file and references the elements/types and the group. The reference is done by ```<xs:group ref="DefaultData"/>``` in both files. 
Looking at the generated file there is unfortunately no interface generated for the group. Am I dooing something wrong or is this an issue with the tool?

Version of the tool i have used is 2.0.230.

Created some sample files to demonstrate my issue. I have attached the files. Attached also the files that was generated by the tool.

[XMLSerialization.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/3014218/XMLSerialization.zip)

The commands to generate the C# files i have used are:
```
XmlSchemaClassGenerator.Console.exe -n "=DefaultData" -v -o . DefaultData.xsd
XmlSchemaClassGenerator.Console.exe -n "=RequestData" -v -o . RequestData.xsd
```

Thanks a lot 
Regards Boris

**Comment by mganss** [comment]
This case was not supported so far, only where the group was referenced from a derived class. I have fixed this in 2.0.232.

**Comment by borzag** [comment]
Thanks for the fast reply and the fix.
Running the second console command in my [first post](https://github.com/mganss/XmlSchemaClassGenerator/issues/109#issue-426053806):
`XmlSchemaClassGenerator.Console.exe -n "=RequestData" -v -o . RequestData.xsd`
works fine. Running the first command in my first post:
`mlSchemaClassGenerator.Console.exe -n "=DefaultData" -v -o . DefaultData.xsd`
unfortenately generates an exception. The `DefaultData.xsd `references an `<group>` and an `<attributeGroup>` directly under a `<complexType>`

Here are the stack trace of the exception:
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'XmlSchemaClassGenerator.ClassModel' to type 'XmlSchemaClassGenerator.InterfaceModel'.
   at XmlSchemaClassGenerator.ModelBuilder.<CreateTypeModel>b__12_1(XmlSchemaGroupRef i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at XmlSchemaClassGenerator.ModelBuilder.CreateTypeModel(Uri source, XmlSchemaComplexType complexType, NamespaceModel namespaceModel, XmlQualifiedName qualifiedName, List`1 docs)
   at XmlSchemaClassGenerator.ModelBuilder.CreateTypeModel(Uri source, XmlSchemaAnnotated type, XmlQualifiedName qualifiedName)
   at XmlSchemaClassGenerator.ModelBuilder..ctor(GeneratorConfiguration configuration, XmlSchemaSet set)
   at XmlSchemaClassGenerator.Generator.Generate(XmlSchemaSet set)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)
```

**Comment by mganss** [comment]
This occurs because the names of the element and the group are the same (`DefaultData`). This is currently not supported. It works if you rename either the element or the group, or put them in different namespaces.

**Comment by borzag** [comment]
Ahh

Renamed the element to something else and then it worked like a charm! 
Thanks a lot for all the nice help from you! 

Regards Boris
