### ISSUE TITLE
Issue #109 is only partly resolved

### ISSUE THREAD

**Issue by borzag** [mganss/XmlSchemaClassGenerator#110]
[Issue #109](https://github.com/mganss/XmlSchemaClassGenerator/issues/109#issuecomment-477910806) is fixed for one case but not for the other. See the error description and stack trace out put in [this post](https://github.com/mganss/XmlSchemaClassGenerator/issues/109#issuecomment-477910806)

**Comment by mganss** [comment]
I'll reopen #109 and close this.
