### ISSUE TITLE
Namespace collision with members called "System"

### ISSUE THREAD

**Issue by cauer-feynsinn** [mganss/XmlSchemaClassGenerator#111]
There is a collision when there is an Attribute called System, which generates, e.g.:
```csharp
[System.ComponentModel.DescriptionAttribute("Some description")]
[System.Xml.Serialization.XmlAttributeAttribute("system", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
public string System { get; set; }
````
Generated from

```xml
<xs:attribute name="system" type="xs:string">
	<xs:annotation>
	<xs:documentation>Some description.</xs:documentation>
	</xs:annotation>
</xs:attribute>
```
This causes a compile error: CS0120: An object reference is required for the non-static field, method, or property 'SomeClassName.System'. (using mono compiler)

Note that in the attribute constructor `System.Xml.Schema.XmlSchemaForm.Unqualified` is referenced which causes the compiler to think that this can be found under the member `System`.

**Possible Fix:** Explicitly reference the namespace System by prepending `global::`, i.e.,
```csharp
[System.ComponentModel.DescriptionAttribute("Some description")]
[System.Xml.Serialization.XmlAttributeAttribute("system", Form=global::System.Xml.Schema.XmlSchemaForm.Unqualified)]
public string System { get; set; }
```
In general, referencing any namespace should be prepended by `global::`

**Comment by mganss** [comment]
Please use `--codeTypeReferenceOptions=GlobalReference` for this.
