### ISSUE TITLE
vstst.xsd leads to not compilable and deserializable code

### ISSUE THREAD

**Issue by TFTomSun** [mganss/XmlSchemaClassGenerator#119]
I tried to generate code for the official schema of microsoft's test result schema, which can be found here or inside the Visual Studio installation: 
https://github.com/iinteractive/IInteractive.WebTest/blob/master/IInteractive.WebConsole/Schema/Microsoft.VisualStudio.TestTools.Common.Xml.VSTST.xsd

Unfortunately the generator does not handle the schema well. Some types are missing and the deserialization returns null by default.

**Comment by mganss** [comment]
You can get it compile using the configuration options `TextValuePropertyName` (e.g. set to "TextValue") and `GenerateComplexTypesForCollections = true`. The latter is not currently surfaced on the command line  🙄 I'll add this shortly.

Do you have an example XML?

**Comment by TFTomSun** [comment]
I can not provide a full example but you can try it with this one:
```xml
<TestRun id="405373d8-071e-492c-979e-298ffa45d868" name="xxx 2019-07-05 16:35:49:197" runUser="xxx" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2019-07-05T16:35:49.2219214+02:00" queuing="2019-07-05T16:35:49.2219214+02:00" start="2019-07-05T16:35:48.1118483+02:00" finish="2019-07-05T16:35:49.2346292+02:00" />
  <TestSettings name="default" id="b51114f8-63f6-4b94-baf7-90c3c9af759d">
    <Deployment runDeploymentRoot="xxx_2019-07-05_16_35_49_197" />
  </TestSettings>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="0" executed="0" passed="0" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut></StdOut>
    </Output>
    <RunInfos>
 
    </RunInfos>
  </ResultSummary>
</TestRun>



```

**Comment by mganss** [comment]
I've noticed there are 2 types (`LoadTestType` and `CounterSetMappings`) which are sequences with more than one element and `maxOccurs="unbounded"`. This can result in schema-invalid serialization output but isn't a problem when deserializing.

**Comment by TFTomSun** [comment]
I think the issue is more related to the schema namespace settings:
This is how I do it at the moment. Btw. How can I define a file name? Currently the filename == the namespace.

```csharp
  var xsdSchemaFile = ...
                 
           var generator = new Generator
            {

                OutputFolder = xsdSchemaFile.Directory.FullName,
                Log = s => Console.Out.WriteLine(s),
                GenerateNullables = true,
                NamespaceProvider = new Dictionary<NamespaceKey, string>
                    {
                        { new NamespaceKey("http://microsoft.com/schemas/VisualStudio/TeamTest/2010"), "Siemens.Collaboration.Net.CliAutomation.Dotnet" }
                    }
                    .ToNamespaceProvider(x => null),

                TextValuePropertyName ="TextValue",
                GenerateComplexTypesForCollections=true,
                 
            };

            generator.Generate(xsdSchemaFile.FullName.To().Enumerable());
```

**Comment by mganss** [comment]
Deserialization works for me using code like this:

```c#
var s = new XmlSerializer(typeof(Schemas.VisualStudio.TeamTest.TestRunType));
var sr = new StringReader(xml);
var o = s.Deserialize(sr);
```

**Comment by TFTomSun** [comment]
yeah.. just checked it and seems to work for me now to. Maybe i broke it when i manually changed the generated code before. I'll use the generated code now and come back if there are still issues.

Many thanks for the fast response :)

**Comment by TFTomSun** [comment]
Ah... I would still like to know how i can customize the generated file name while preserving the defined namespace.

**Comment by mganss** [comment]
You'll have to pass a custom `OutputWriter` to the generator. Best idea probably is to derive from `FileOutputWriter` and override `Write()`:
https://github.com/mganss/XmlSchemaClassGenerator/blob/b77115361340cb93cb18d9506a0de63fe5cc75d3/XmlSchemaClassGenerator/FileOutputWriter.cs#L28-L37
