### ISSUE TITLE
Private setter in base class lead to deserialization issues

### ISSUE THREAD

**Issue by TFTomSun** [mganss/XmlSchemaClassGenerator#121]
Some properties are generated using a private setter. The xml serializer can't deserialize those properties, when they are defined in a base class. Please provide a switch to make all setters public.

**Comment by mganss** [comment]
Can you provide a quick example?

**Comment by Rubbiroid** [comment]
I would suggest to add a cli argument to specify visibility of such props, as it is easier to initialize collections together with other props and not in separate line.

**Comment by mganss** [comment]
Implemented in #189
