### ISSUE TITLE
Add a command line option to map `xs:anyUri` to `System.Uri`

### ISSUE THREAD

**Issue by Pretasoc** [mganss/XmlSchemaClassGenerator#146]
I just used the tool with an schema that contains `xs:anyUri` types and was suprised, that in the generated classes that field was an `string`. I guess thats becasue of the behaviour of `xsd.exe` and to maintain compatibility. So my suggestion is to add an flag to the command line with the default value of false to enable the mapping of `xs:anyUri` to `System.Uri`.

**Comment by mganss** [comment]
Have you tried if this works with XmlSerializer?

**Comment by Pretasoc** [comment]
I just tried it, and its not supported without some boilerplate code, that again maps the `Uri` to/from a string.
