### ISSUE TITLE
Generated classes for GML 3.2.1 xsd fail to build

### ISSUE THREAD

**Issue by tilmanb** [mganss/XmlSchemaClassGenerator#150]
I generated classes from the XSD for GML 3.2 (Geography Markup Language) using the binary build of the SchemaClassGenerator and the following command line:

    XmlSchemaClassGenerator.Console.exe -o "d:\temp\gml321" -v http://schemas.opengis.net/gml/3.2.1/gml.xsd

I added these classes to an empty project in Visual Studio 2017 and tried to build that project.

I get these errors in the output (sorry, they are in german, no english version of VS installed):

> "Extended" implementiert den Schnittstellenmember "IExtendedModel.Title" nicht. "Extended.Title" hat nicht den entsprechenden Rückgabetyp "TitleEltType" und kann "IExtendedModel.Title" daher nicht implementieren.

The file referenced is the generated Xlink.cs .

Can this be solved by specifying command line switches to the generator, or is it a generator bug?

**Comment by mganss** [comment]
There was a problem with included schemas which I have fixed in 2.0.310. The generated files compile now but you need to disable generation of interfaces using the `-t-` command line option.

**Comment by tilmanb** [comment]
Thanks, this works!
