### ISSUE TITLE
How to output one file per class generated?

### ISSUE THREAD

**Issue by jzabroski** [mganss/XmlSchemaClassGenerator#158]
Would make merge conflicts simpler to understand for large XSDs (2724 lines long XSD generates 5,581 line long C# file).

I'm sure there are probably good reasons to keep it all in one file, but I would really prefer to generate multiple files.

**Comment by mganss** [comment]
This is currently not possible. You can generate separate files for different XML namespaces and XSD input files, see https://github.com/mganss/XmlSchemaClassGenerator#mapping-xsd-files-to-c-namespaces

If you're using the library you can use the `OutputWriter` property to define a custom output method.

**Comment by LightosTomJ** [comment]
Michael. Did you close this issue due to amount of work required to achieve it or that multiple `XmlSchema` link in such a way that make it impossible to separate one class per output ".cs" file?

**Comment by mganss** [comment]
This issue is still open. The "Closed" status indicator preceding your comment refers to PR #174. Did you mean that?

**Comment by LightosTomJ** [comment]
Yep sorry, I thought that PR #147 meant that this issue was closed, I got that wrong. Still quite new to GitHub (and git generally).

I have started to develop this feature via a new branch:

> 158-Output-one-file-per-class

I will be adding 'Commits' in due course. Let me know when you want this branch to be published for review.

**Comment by mganss** [comment]
@LightosTomJ Thanks. You can make a PR whenever you feel it's ready to be merged. Also, when you make a PR it's not cast in stone, i.e. you can still add commits after submitting. Please add unit tests.

**Comment by jzabroski** [comment]
@LightosTomJ Happy to help test it and give feedback when you're done.  We love this .NET Core Tool and this is probably the one feature we would love to see added.

**Comment by jzabroski** [comment]
@LightosTomJ If you want help learning how to create a PR, too, check out my GitHubTips page on my "Home" repository: https://github.com/jzabroski/Home/blob/master/GitHubTips/README.md

**Comment by mganss** [comment]
This feature is now implemented (see #177)

**Comment by jzabroski** [comment]
Sweet, can't wait to try it in the coming weeks.
