### ISSUE TITLE
Disable german language comments

### ISSUE THREAD

**Issue by jzabroski** [mganss/XmlSchemaClassGenerator#160]
```c#
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Snapshots" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Snapshots" /> class.</para>
        /// </summary>
```

**Comment by mganss** [comment]
It's currently not possible to selectively disable comments in a specific language. You can only disable comments altogether using `--dc`. This option could be expanded into a list of languages and an `auto` setting that that takes the current culture into account.

**Comment by mganss** [comment]
There's now the `--cl` flag to set the comment languages.
