### ISSUE TITLE
Namespace mapping with includes

### ISSUE THREAD

**Issue by Falco20019** [mganss/XmlSchemaClassGenerator#17]
When including files with only types and no elements, the namespaces won't get mapped properly. This is due to the fact, that in `Generator.BuildModel()`, the `GlobalElements` get processed before the `GlobalTypes`. I swapped the order to get it working and had no problems using it.

Before, all included types got included into the namespace of the includer. Therefore, I ended with multiple copies of the same type, distributed between different namespaces.

**Comment by mganss** [comment]
Thanks for reporting this!
