### ISSUE TITLE
Can configure the CLR type for XML Datetime

### ISSUE THREAD

**Issue by emmanuelbenitez** [mganss/XmlSchemaClassGenerator#171]
We would like to have possibility the generate class having [DateTimeOffset](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset?view=netframework-4.8) when the XML element type is datetime.

**Comment by mganss** [comment]
AFAICT `XmlSerializer` doesn't support `DateTimeOffset`.

**Comment by emmanuelbenitez** [comment]
You're right but it is possible create your own [IXmlSerializable](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.ixmlserializable?view=netframework-4.8). 

- [Example of implementation](https://github.com/icraftsoftware/BizTalk.Factory/blob/master/src/BizTalk.Common/Xml/RuntimeTypeXmlSerializer.cs)
- [Exemple of usage](https://github.com/icraftsoftware/BizTalk.Factory/blob/master/src/BizTalk.Pipeline.Components/MicroComponent/ContextBuilder.cs) line 75

**Comment by mganss** [comment]
Can you provide an example how this would work with DateTimeOffset?

**Comment by emmanuelbenitez** [comment]
This link provide a good sample: [link](https://stackoverflow.com/a/8138762)

**Comment by mganss** [comment]
This means we would have to make the type configurable as a string, e.g. `MyTypes.MyDateTimeOffset`. Currently types are handled internally as objects of `Type`, i.e. the type needs to be known at compile time. Or do you think this could be handled differently?

**Comment by bcallaghan-et** [comment]
This seems like a good fit for the MemberVisitor action that can be specified on the Generator. I tried to use the visitor pattern to configure `xs:date` as SQL `date` and `xs:dateTime` as SQL `datetime2(0)` using the `Column` attribute. Unfortunately, I discovered that the `Nullable<DateTime>` property can't be visited. Please allow the nullable property to be visited, since that's the one that Entity Framework can actually use.

**Comment by mganss** [comment]
@bcallaghan-et This should be possible now.

**Comment by bcallaghan-et** [comment]
@mganss Yes, I can now configure the column type of the `Nullable<DateTime>` properties through `MemberVisitor`. Thanks!

**Comment by heggi** [comment]
I think we need a flag that will replace standard generated code 
```
[System.Xml.Serialization.XmlElement("RequestTime")]
public System.DateTime RequestTime { get; set; }
```

with workaround code
```
[System.Xml.Serialization.XmlIgnore]
public System.DateTimeOffset RequestTime { get; set; }

[System.Xml.Serialization.XmlElement("RequestTime")]
public string RequestTimeString {
       get => RequestTimeOffset.ToString("o");
       set => RequestTimeOffset = System.DateTimeOffset.Parse(value);
}
```

**Comment by mganss** [comment]
@heggi Wouldn't this also have to account for the different XML schema types in the `ToString()` call (date, time, datetime)? Also, we might want to use `TryParse()`. Can you make a PR?

**Comment by fgheysels** [comment]
Any update on this ? 
Is this something that is being considered ?  I think it makes sense to implement the solution that was posted by @heggi [here](https://github.com/mganss/XmlSchemaClassGenerator/issues/171#issuecomment-667558182)
