### ISSUE TITLE
Wrong XmlSchemaClassGenerator version number in generated code

### ISSUE THREAD

**Issue by modmynitro** [mganss/XmlSchemaClassGenerator#173]
I updated the generator from version 2.0.232 to version 2.0.345.
After this the version number inside the generated code was 2.0.0.0 instead of the ecpected 2.0.345.0.

__2.0.232__
```csharp
// This code was generated by XmlSchemaClassGenerator version 2.0.232.0.
[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.232.0")]
```
__2.0.345__
```csharp
// This code was generated by XmlSchemaClassGenerator version 2.0.0.0.
[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
```

It seems this behavior started with v2.0.252.

**Comment by mganss** [comment]
This was introduced when the assembly version was made to include only the major version. I've fixed it to display the assembly file version which reflects the release version.

**Comment by modmynitro** [comment]
Thy for the quick fix.
