### ISSUE TITLE
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.

### ISSUE THREAD

**Issue by GitMyCode** [mganss/XmlSchemaClassGenerator#175]
I have dotnet core 3 installed and it seems i cannot run the tool with it

is it supposed to be supported?
```

dotnet new tool-manifest
dotnet tool install dotnet-xscgen
dotnet xscgen

It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.1 at [/Users/me/.dotnet/shared/Microsoft.NETCore.App]
```

**Comment by mganss** [comment]
This occurs because .NET Core tools are [framework-dependent](https://docs.microsoft.com/en-us/dotnet/core/tools/troubleshoot-usage-issues#runtime-not-found). I've added netcoreapp3.1 as a target framework.
