### ISSUE TITLE
UnauthorizedAccessException Error on "XmlSchemaClassGenerator.Generator().Generate(files))

### ISSUE THREAD

**Issue by TomJamesAtDataSummit** [mganss/XmlSchemaClassGenerator#176]
Hi. I am trying to convert multiple ".xsd" files, via:

_For use from code use the [library NuGet package](https://www.nuget.org/packages/XmlSchemaClassGenerator-beta/)_:
```
var generator = new Generator
{
    OutputFolder = outputFolder,
    Log = s => Console.Out.WriteLine(s),
    GenerateNullables = true,
    NamespaceProvider = new Dictionary<NamespaceKey, string> 
    { 
        { new NamespaceKey("http://wadl.dev.java.net/2009/02"), "Wadl" } 
    }
    .ToNamespaceProvider(new GeneratorConfiguration { NamespacePrefix = "Wadl" }.NamespaceProvider.GenerateNamespace)
};

generator.Generate(files);
```

However, I receive folder and file access errors:

> System.UnauthorizedAccessException: Access to the path 'C:\Users\XXXX\Downloads' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>    at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
>    at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
>    at System.Xml.XmlTextReaderImpl.FinishInitUriString()
>    at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
>    at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
>    at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
>    at XmlSchemaClassGenerator.Generator.<>c__DisplayClass94_0.<Generate>b__0(String f)
>    at System.Linq.Enumerable.WhereSelectListIterator 2.MoveNext()
>    at XmlSchemaClassGenerator.Generator.Generate(IEnumerable 1 files)
>    at XMLConverter.Program.Main(String[] args) in C:\MySoftware\Program.cs:line 56

I have tried this in different directories but to no avail:
- SharePoint directory
- C:\ (root directory)
- C:\Users\XXXX\Downloads

I am deleting and creating directories within the same routine separately to the "Generator.Generate()" method. The issue only occurs via the "Generator.Generate()" call. How can the file access permissions be satisfied (or bypassed!!)?

**Comment by mganss** [comment]
This occurs during `XmlReader.Create()`. Does creating an `XmlReader` for your xsd files work from your code?

**Comment by TomJamesAtDataSummit** [comment]
The `XmlReader.Create()` suggestion did throw an error (it was a directory, not a file), this has been corrected. 

The next problem is that the "Generator.Generate()" appears to be looking for another directory, within the project 'debug' folder, which I can only assume is happening via your code. I don't know if this is a temporary location for auto-generated code but nothing in my code below is trying to write to the project debug output folders.

The files I am trying to convert are [here](https://github.com/mganss/XmlSchemaClassGenerator/files/4403803/schema.zip). My solution is:
```
namespace XMLConverter
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                string outFile = @"C:\tmp\";
                DirectoryInfo diOutput = Directory.GetParent(outFile);
                DirectoryInfo diSchema = Directory.GetParent(@"C:\Users\----HIDDEN----\schema\");

                var g = new Generator();
                g.OutputFolder = diOutput.FullName;
                g.Log = s => Console.Out.WriteLine(s);
                g.GenerateNullables = true;

                List<FileInfo> xsdFiles = diSchema.GetFiles().ToList();
                List<string> files = new List<string>();
                //Dictionary<NamespaceKey, string> dNS = new Dictionary<NamespaceKey, string>();

                foreach (var f in xsdFiles)
                {
                    if (f.Extension == ".xsd")
                    {
                        string n = f.Name.Substring(0, f.Name.LastIndexOf("."));
                        if (g.NamespaceProvider == null) g.NamespaceProvider = new NamespaceProvider();

                        XmlReader xr1 = XmlReader.Create(f.FullName);
                        XmlTextReader reader = new XmlTextReader(f.FullName);
                        XmlSchema xs = XmlSchema.Read(reader, ValidationCallback);

                        if (g.NamespaceProvider.Keys.Count(ns => ns.XmlSchemaNamespace == xs.TargetNamespace) == 0)
                        {
                            g.NamespaceProvider.Add(
                                new NamespaceKey(xs.TargetNamespace), n);
                        }
                        
                        files.Add(n);
                        break;
                    }
                }
               g.Generate(files);
            }
            catch (Exception ae)
            {
                string strError = ae.ToString();
                if (ae.InnerException != null) strError = ae.InnerException.Message.ToString();
            }
        }
        static void ValidationCallback(object sender, ValidationEventArgs args)
        {
            if (args.Severity == XmlSeverityType.Warning)
                Console.Write("WARNING: ");
            else if (args.Severity == XmlSeverityType.Error)
                Console.Write("ERROR: ");

            Console.WriteLine(args.Message);
        }
    }
}
```
The error I receive is:
> System.UnauthorizedAccessException: Access to the path 'C:\VSTS\ACompany\XMLConverter\XMLConverter\bin\Debug\genericRailML' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
>    at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
>    at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
>    at System.Xml.XmlTextReaderImpl.FinishInitUriString()
>    at System.Xml.XmlTextReaderImpl..ctor(String uriStr, XmlReaderSettings settings, XmlParserContext context, XmlResolver uriResolver)
>    at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
>    at System.Xml.XmlReader.Create(String inputUri, XmlReaderSettings settings, XmlParserContext inputContext)
>    at XmlSchemaClassGenerator.Generator.<>c__DisplayClass94_0.<Generate>b__0(String f)
>    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    at XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files)
>    at XMLConverter.Program.Main(String[] args) in C:\VSTS\ACompany\XMLConverter\XMLConverter\Program.cs:line 61

**Comment by mganss** [comment]
I think instead of `files.Add(n);` it should be `files.Add(f.FullName);`. Otherwise the files are read from the current working directory which by default is the folder where the exe is located (`...\bin\Debug`).

**Comment by LightosTomJ** [comment]
Yes, `files.Add(f.FullName)` sorted the problem. As an explanation for others, the `files.Add(n);` was removing the file ".xsd" extension and thus generated the errors.

Michael, many thanks for your help, your answers have provide very accurate and easy to understand.
