### ISSUE TITLE
Create SQL Database Table Schemas (not just C# POCOs)

### ISSUE THREAD

**Issue by TomJamesAtDataSummit** [mganss/XmlSchemaClassGenerator#178]
Given the recent separation of classes to a single files via [pull request #177](https://github.com/mganss/XmlSchemaClassGenerator/pull/177), the existing functionality of this [XmlSchemaClassGenerator](https://github.com/mganss/XmlSchemaClassGenerator) will allow for SQL database table schema scripts to be generated, without much additional work.

This [web-page](https://www.c-sharpcorner.com/article/create-sql-server-database-project-with-visual-studio/) (up to step 4), shows the scope this suggestion. The files created from [XmlSchemaClassGenerator](https://github.com/mganss/XmlSchemaClassGenerator) would be dragged and dropped into the '[dbo]' section, rather than importing an existing database.

**Limitations**
- Foreign key relationships would NOT be possible to automate

Is this of interest to people?

**Comment by mganss** [comment]
No, I'd rather keep this project focused on a single task. But of course you're welcome to re-use code in a separate project.

Why would foreign keys not be possible? You'd just have to make sure there is a primary key in all classes/tables. This is what the EF support here does:
https://github.com/mganss/XmlSchemaClassGenerator/blob/f310d23bd7db2dbc6d4666577614860dfc2d7552/XmlSchemaClassGenerator/TypeModel.cs#L366-L386

**Comment by TomJamesAtDataSummit** [comment]
Fair enough.

I want to continue using your solution, as it is the best I've seen for XSD/XML/C# interoperability but do respect that you don't want pull requests remaining open indefinitely and introduce scope 'creeping'. Unfortunately, for my needs, the SQL project class creator is critical. My problem is that I am unable to create my own separate repository and link to your latest code. FYI, I would achieve the proposed enhancement by replicating your `XmlSchemaClassGenerator` project and rename it to 'XmlSchemaSQLClassGenerator`, prior to alterations. 

_Is the following a workaround to the problem:_
If I create a branch on your repository, add commits (not pull request though), will the files remain in GitHub on this separate branch, even without a created pull request and if my laptop fails/catches fire, etc? I want to avoid cluttering your repository but have a cloud back-up of this work. This allows integration at a much later date, should you expand the scope of the repository. I am happy to refactor my code to ensure that it continues to inter-operable with any updates from other branches, hence the reason for me begging to keep this in your repository.

Do you have any alternative workarounds that allows me to continue using your latest code but not interfere with your repository? Regards, Tom.

**Comment by mganss** [comment]
I think a [fork](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) would be ideal for this use case.

**Comment by LightosTomJ** [comment]
Done.
