### ISSUE TITLE
Date types are not serialized correctly

### ISSUE THREAD

**Issue by SierraNL** [mganss/XmlSchemaClassGenerator#18]
I've started using the generator to replace xsd.exe, since I use a large base schema which I don't want duplicated in all sub types. But I've noticed a difference in generated code.

Elements of the following type:
```XML
<xs:simpleType name="LDT_Datum">
	<xs:annotation>
		<xs:documentation>Datum</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:date">
		<xs:pattern value="[^:Z]*"/>
	</xs:restriction>
</xs:simpleType>
```

Get generated as:
```C#
/// <summary>
/// <para>Datum</para>
/// <para>Datum</para>
/// <para xml:lang="en">Pattern: [^:Z]*.</para>
/// </summary>
[System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[^:Z]*")]
[System.Xml.Serialization.XmlElementAttribute("Datum", Namespace="http://www.istandaarden.nl/iwlz/1_2/basisschema/schema/1_2")]
public System.DateTime Datum { get; set; }
```

And xsd.exe adds the following to XmlElementAttribute: DataType = "date"

This difference results in wrongly generated XML, since the time gets generated also.

**Comment by mganss** [comment]
Thanks for reporting this. This occurred only in simple types which were restrictions of XML Schema simple types.
