### ISSUE TITLE
Some properties are never visited by MemberVisitor

### ISSUE THREAD

**Issue by bcallaghan-et** [mganss/XmlSchemaClassGenerator#184]
I am trying to use MemberVisitor to apply additional attributes based on documented rules that are not present in the XSD schema. One roadblock I've run into is that text value properties are not passed into the visitor action. Consider the following schema:
```xml
<complexType name="AmountType">
  <simpleContent>
    <extension base="vsi:MonetaryAmount">
      <attribute name="currency" type="vsi:CurrencyType"/>
    </extension>
  </simpleContent>
</complexType>
```
This generates a C# class with a `Currency` property and a `Value` property. I want to add `[Column(TypeName = "decimal(12,2)")]` on `Value` because it's type is `MonetaryAmount`, but I never get the chance.

Also consider the following C# properties that were generated:
```cs        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
[System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
[System.Xml.Serialization.XmlElementAttribute("MyDate", DataType="date")]
public System.DateTime MyDateValue { get; set; }
        
/// <summary>
/// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die MyDate-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
/// <para xml:lang="en">Gets or sets a value indicating whether the MyDate property is specified.</para>
/// </summary>
[System.Xml.Serialization.XmlIgnoreAttribute()]
[System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute()]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
public bool MyDateValueSpecified { get; set; }
        
[System.Xml.Serialization.XmlIgnoreAttribute()]
public System.Nullable<System.DateTime> MyDate
{
    get
    {
        if (this.MyDateValueSpecified)
        {
            return this.MyDateValue;
        }
        else
        {
           return null;
        }
    }
    set
    {
        this.MyDateValue = value.GetValueOrDefault();
        this.MyDateSpecified = value.HasValue;
    }
}
```
I would like to add `[Column(TypeName = "date")]` to `MyDate` because it's XML type is `date` and to use it with Entity Framework. However, that property is never passed into the `MemberVisitor` action. The other two properties are, but EF will (correctly) ignore those properties.

**Comment by mganss** [comment]
I've added a few more calls that should allow for your scenario.

**Comment by bcallaghan-et** [comment]
Yes, I can now add the `Column` attributes that I wanted through `MemberVisitor`. Thanks!
