### ISSUE TITLE
Allow Integer override type only for unspecified values.

### ISSUE THREAD

**Issue by bcallaghan-et** [mganss/XmlSchemaClassGenerator#185]
By default, the library will use the `totalDigits` facet to determine the correct CLR type for `xs:integer`. Users can set their own type for `xs:integer`, but that type is used for all integers, and not just those that have undetermined lengths. I would like to see an option where the user's type is used only when a better type cannot be determined, such as when the `totalDigits` facet is not present.

**Comment by bcallaghan-et** [comment]
My first thought is that the user type could be used [here](https://github.com/mganss/XmlSchemaClassGenerator/blob/master/XmlSchemaClassGenerator/CodeUtilities.cs#L73) and then use `string` as a double-fallback. The check at the top of the function would then be removed so that processing can continue, even in the presence of a user-selected type. Would there be any negative repercussions to this change?

**Comment by mganss** [comment]
It would no longer allow for the use case where you want your preferred type to be used even if there are restrictions (knowing, perhaps, that in reality an `int` will always suffice and you don't want to deal with `string`s for numeric values). Maybe we can add another configuration option that allows for this scenario.

**Comment by mganss** [comment]
The current behavior was introduced in response to #89.

**Comment by bcallaghan-et** [comment]
Looking back at #89 I see that the OP only suggested using the consumer-defined type if the integer was too long and string would otherwise be used. That's exactly what I'm suggesting as well. Other members of my team have suggested using `long` as the fallback type, but they still want to see the intelligent logic checking against the total digits.

A new configuration option allowing the consumer to select between the two modes would work for me. Something like `UseIntegerDataTypeAsFallback`, with a default setting of `false` would support my scenario without changing existing consumers.

**Comment by bcallaghan-et** [comment]
I started working on this, and I found that many of my integers have `minInclusive` and `maxInclusive` facets (but not `totalDigits`). It's certainly useful to me if those restrictions are considered when determining the correct data type. Is this something you would want to include by default? Or should it be locked behind a new configuration option?

**Comment by mganss** [comment]
Sounds like a very good idea to include this by default (no extra configuration option).
