### ISSUE TITLE
Resulting classes have inconsistent line endings

### ISSUE THREAD

**Issue by SierraNL** [mganss/XmlSchemaClassGenerator#19]
When I open the resulting .cs files I get the following message in Visual Studio 2015 Enterprise

![image](https://cloud.githubusercontent.com/assets/2605717/20965353/8aa63570-bc75-11e6-9d3f-78fc3284d2d0.png)

It seems the line endings are inconsistent, where I (and Visual Studio) would expect \r\n.

**Comment by mganss** [comment]
Thanks for reporting this. This was due to AppVeyor having Git's autocrlf setting set to "input" instead of "true" by default. Fixed in 1.0.34.
