### ISSUE TITLE
Prevent generating ID property

### ISSUE THREAD

**Issue by pmeems** [mganss/XmlSchemaClassGenerator#202]
How do I prevent the generation of the ID property in every class?
```
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public long Id { get; set; }
```

This field is not in the XSD.

And I'm using the generated classes to read XML-files, so I also don't need the DataAnnotations and Serialization tags above my property:
```
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(24)]
        [System.Xml.Serialization.XmlElementAttribute("Str")]
```
How to prevent those the be generated?

I do have to say I really like this tool. It will help me avoid creating those classes by hand.

**Comment by mganss** [comment]
To prevent the `Id` property, don't use the `-f` flag. The DataAnnotations attributes cannot be disabled specifically currently, but they get disabled along with a few other attributes when you specify `-c` (`--pcl`).

**Comment by pmeems** [comment]
Thanks. I've got rid of the `Id` property now.
Using `--pcl` does remove these lines:
`[System.SerializableAttribute()]`
`[System.Diagnostics.DebuggerStepThroughAttribute()]`
`[System.ComponentModel.DesignerCategoryAttribute("code")]`
above the class, so that is helpfull.

Each property still has `[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]`. But I can live with that.

Thanks again for this great tool.
