### ISSUE TITLE
Model state is invalid if do not pass the values for elements minoccurs=0

### ISSUE THREAD

**Issue by pavan1386** [mganss/XmlSchemaClassGenerator#206]
For httppost request [frombody] Model state is invalid if we do not pass the values for elements minoccurs=0. Any work around to achieve this

**Comment by pavan1386** [comment]
if i don't specify element "SrcSbTp" in the request it says model state is invalid even though it is minoccurs = 0

<xs:element name="SrcSbTp" type="Max35Text" minOccurs="0" maxOccurs="1" />

**Comment by mganss** [comment]
Please provide more context. I gather you're using a generated type as a parameter in an ASP.NET action? What does the generated code look like? What's the signature of your action method? What is the error message?
