### ISSUE TITLE
Incorrect code generation for unbounded choice

### ISSUE THREAD

**Issue by fbrier** [mganss/XmlSchemaClassGenerator#208]
In a schema with a root element defined first as a complex type that contains an unbounded choice of several other elements (some defined first as complexType(s)) which have minOccurs 0, the XmlSchemaClassGenerator creates a list for each type of element vs. a single array of object.

```xml
	<xs:complexType name="T_rootnode">
		<xs:choice maxOccurs="unbounded">
			<xs:element ref="elem1" minOccurs="0"/>
			<xs:element ref="elem2" minOccurs="0"/>
			<xs:element ref="elem3" minOccurs="0"/>
			<xs:element ref="elem4" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>

```
I double checked this code generating using xsd.exe. The xsd.exe generated:
```csharp
    public partial class T_rootnode {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("elem1", typeof(T_elem1))]
        [System.Xml.Serialization.XmlElementAttribute("elem2", typeof(T_elem2))]
        [System.Xml.Serialization.XmlElementAttribute("elem3", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("elem4", typeof(T_elem4))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
```
xscgen generated:
```csharp
        public T_rootnode()
        {
            this._elem1 = new System.Collections.ObjectModel.Collection<T_Elem1>();
            this._elem2 = new System.Collections.ObjectModel.Collection<T_Elem2>();
            this._elem3 = new System.Collections.ObjectModel.Collection<string>();
            this._elem4 = new System.Collections.ObjectModel.Collection<T_Elem4>();
        }

        private System.Collections.ObjectModel.Collection<T_Elem1> _elem1;
        private System.Collections.ObjectModel.Collection<T_Elem2> _elem2;
        private System.Collections.ObjectModel.Collection<string> _elem3;
        private System.Collections.ObjectModel.Collection<T_Elem4> _elem4;
```
Could you please confirm this issue? Thank you.

**Comment by fbrier** [comment]
Never mind. I really need this because the legacy XML can have elements out of order in a sequence, and I needed to preserve the order of those elements. I started reading through the XmlSchemaClassGenerator classes. Looked for more doc, and found the comment in the README.md saying it just treats choices as sequences. XmlSpy considers an unbounded choice valid schema. It would have been nice if this tool generated the same code as xsd.exe.

**Comment by mganss** [comment]
Yes, that's an issue which has existed from the start. When deserializing, the order of elements within each collection is preserved, though obviously not the overall order. It would be nice if someone could contribute code to optionally generate code like xsd.exe.
