### ISSUE TITLE
Generating Array properties

### ISSUE THREAD

**Issue by Ekkeir** [mganss/XmlSchemaClassGenerator#211]
Hi,
Is it possible to generate properties as `Array`s as opposed to `Collection<T>`s?

There're some old classes that seem to have been generated via some older version of XmlSchemaClassGenerator, that I need to update for newer xsd's, while retaining as much as possible for compatibility. Yet, try as I might, I cannot find a way to generate array'ed properties.
I've tried setting `CollectionImplementationType` & `CollectionType` Generator properties to `Array`, but those attempts ended up with "non generic type" exception.

Is there something I'm missing?

Thank you in advance.

**Comment by mganss** [comment]
This didn't work up until now but I've pushed a fix. To use plain arrays, specify `--ct=System.Array` and also be sure to use `--csm=PublicWithoutConstructorInitialization` or `--csm=Public`.

**Comment by Ekkeir** [comment]
Thank you so much. Really appreciate it.
