### ISSUE TITLE
Support for linked XSD's

### ISSUE THREAD

**Issue by DirkSchwa** [mganss/XmlSchemaClassGenerator#215]
Hi there, question:

I have this big ball of XSD's which are all linked (using import and include).
The set contains around 80 XSD's.

My goal is to point to a single XSD and let the generator use import and include to do the rest.

Is this situation supported?
I want to avoid to manually list all the required XSD's.

**Comment by mganss** [comment]
Yes, this is supported.

**Comment by DirkSchwa** [comment]
Thanks for the reply, it appears I was using the wrong XSD to start the generation. Talking about finding the needle in the haystack.
