### ISSUE TITLE
NuGet library not generating C# classes from multiple xsd files

### ISSUE THREAD

**Issue by gojanpaolo** [mganss/XmlSchemaClassGenerator#228]
```c#
new Generator
{
    NamespacePrefix = "Foo"
}
.Generate(new[]{ "file1.xsd", "file2.xsd" });
```

... does not generate a .cs file

No exceptions are thrown and the method just finishes silently.

.cs file will be generated if I leave only one file. Either of the files worked by itself.

**Comment by gojanpaolo** [comment]
It might be because I'm getting

```
The global element '...' has already been declared.
The complexType '...' has already been declared.
The simpleType '...' has already been declared.
```

xsd.exe handles those properly though.

**Comment by mganss** [comment]
You can set the `Log` property of the `Generator` to see if there are validation issues. 

Is one of the files dependent on the other? If so, you need to specify only the schema file that depends on the other one. The generator will still generate classes for the combined schema set.
