### ISSUE TITLE
System does not support Windows-1250 encoding

### ISSUE THREAD

**Issue by Ross-cz** [mganss/XmlSchemaClassGenerator#229]
I tried to use a tool like this:
& "$Env:USERPROFILE\.dotnet\tools\xscgen" some.xsd
It crashed with error:
Unhandled exception. System.Xml.XmlException: System does not support 'Windows-1250' encoding. Line 1, position 31.
...

XSD contains specific encoding XML declaration:
`<?xml version="1.0" encoding="Windows-1250"?>`

Maybe it needs to call this?
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

**Comment by mganss** [comment]
Thanks, fixed.
