### ISSUE TITLE
Wrong usage of default options

### ISSUE THREAD

**Issue by zoligorbe** [mganss/XmlSchemaClassGenerator#230]
Hi,

First of all thank you for your tool, it's really useful.
I've noticed that I'm unable to turn off some default options in the console tool and I think there is a bug in the options handling.
For every parameter where the default value is _true_ you should evaluate the settings with _v == null_ instead of _v != null_.

**Comment by mganss** [comment]
You can disable options that are enabled by default by using e.g. `-a-`.
