### ISSUE TITLE
Collection type cannot specify assembly name

### ISSUE THREAD

**Issue by erichentspanndich** [mganss/XmlSchemaClassGenerator#235]
The --collectionType parameter does not allow to specify collection types that come from a specific assembly, e.g. when trying to specify the collection type 'System.Collections.ObjectModel.ObservableCollection`1', a System.TypeLoadException exception is thrown stating the type 'System.Collections.ObjectModel.ObservableCollection`1' cannot be found in the assembly 'XmlSchemaClassGenerator.Console' because it is actually located in the assembly 'System.ObjectModel'.

**Comment by mganss** [comment]
You must specify the assembly-qualified name like so: ``--ct="System.Collections.ObjectModel.ObservableCollection`1, System.ObjectModel"``

**Comment by erichentspanndich** [comment]
Thanks a lot, that worked.
