### ISSUE TITLE
How to generate C# for UBL-Order-2.1.xsd of Oasis?

### ISSUE THREAD

**Issue by V4A001** [mganss/XmlSchemaClassGenerator#238]
XmlSchemaClassGenerator.Console.exe https://docs.oasis-open.org/ubl/os-UBL-2.1/xsd/maindoc/UBL-Order-2.1.xsd -verbose

Error:
`Unhandled Exception: System.ArgumentException: Namespace urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2 not provided through map or generator.
   at XmlSchemaClassGenerator.ModelBuilder.BuildNamespace(Uri source, String xmlNamespace)
   at XmlSchemaClassGenerator.ModelBuilder.CreateNamespaceModel(Uri source, XmlQualifiedName qualifiedName)
   at XmlSchemaClassGenerator.ModelBuilder.CreateTypeModel(Uri source, XmlSchemaAnnotated type, XmlQualifiedName qualifiedName)
   at XmlSchemaClassGenerator.ModelBuilder.CreateTypes(IEnumerable`1 types)
   at XmlSchemaClassGenerator.ModelBuilder..ctor(GeneratorConfiguration configuration, XmlSchemaSet set)
   at XmlSchemaClassGenerator.Generator.Generate(XmlSchemaSet set)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)`

**Comment by mganss** [comment]
You need to provide a C# namespace name for the XML schema namespace `urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2`, e.g. by specifying `-n urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2=CoreComponentTypeSchemaModule` on the command line.

**Comment by V4A001** [comment]
Thank you. Danke! Would 'harvesting' the url's itself be a new feature? Seems to be a lot, with the last I get error 'The URI prefix is not recognized.': 
`XmlSchemaClassGenerator.Console.exe https://docs.oasis-open.org/ubl/os-UBL-2.1/xsd/maindoc/UBL-Order-2.1.xsd -verbose -n urn:un:unece:uncefact:data:specification:CoreComponentTypeSchemaModule:2=CoreComponentTypeSchemaModule -n urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2=UnqualifiedDataTypes -n urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2=CommonBasicComponents -n urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2=CommonAggregateComponents urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2=SignatureBasicComponents -n http://www.w3.org/2000/09/xmldsig#=xmldsig`

**Comment by mganss** [comment]
There's a `-n` missing before `urn:oasis:names:specification:ubl:schema:xsd:SignatureBasicComponents-2=SignatureBasicComponents`.

By harvesting you mean generate C# namespace names from XML Schema namespace names automatically? Yes, we're doing that already, though it's not very sophisticated: https://github.com/mganss/XmlSchemaClassGenerator/blob/3c0b48576f617dd67653f89068fcf7e524c8fc97/XmlSchemaClassGenerator.Console/Program.cs#L156-L163
