### ISSUE TITLE
consider "using System.Collections.ObjectModel;"

### ISSUE THREAD

**Issue by emaschas** [mganss/XmlSchemaClassGenerator#242]
The "using System.Collections.ObjectModel;" statement is present at the beggining of the output file but then all the collections declarations include "System.Collections.ObjectModel.Collection<...>" ?
Is it possible to change to just "Collection<...>" ?
Maybe to have an option for that ?

**Comment by mganss** [comment]
I've added the `--cn` flag in 2.0.488 to enable this.

**Comment by emaschas** [comment]
Thank you.
