### ISSUE TITLE
generating unusuable deserialization code.

### ISSUE THREAD

**Issue by frankhommers** [mganss/XmlSchemaClassGenerator#245]
Hi there,

This command: 
`dotnet-xscgen --sf http://schemas.opengis.net/wfs/2.0/wfs.xsd --prefix=MyNamespace`
leads to uncompilable code.

Is there something I can do about this?

Thanks.

**Comment by frankhommers** [comment]
Seems like the same as #150. Let's try again ;-)

**Comment by frankhommers** [comment]
Now it compiles. But I can't deserialize anything.... It seems that it generates duplicate things.

**Comment by frankhommers** [comment]
```csharp
using System;
using System.IO;
using System.Net.Http;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace WFSTest
{
  public class Program
  {
    public static async Task<int> Main(string[] args)
    {
      HttpClient httpClient = new HttpClient();
      HttpResponseMessage result = await httpClient.GetAsync("https://geodata.nationaalgeoregister.nl/kadastralekaart/wfs/v4_0?service=WFS&request=GetCapabilities");
      XmlSerializer serializer = new XmlSerializer(typeof(WFS_CapabilitiesType));
      string resultString = await result.Content.ReadAsStringAsync();
      MemoryStream ms = new MemoryStream(System.Text.Encoding.UTF8.GetBytes(resultString));
      var resultObj = (WFS_CapabilitiesType)serializer.Deserialize(ms);
      return 0;
    }
  }
}
```

**Comment by frankhommers** [comment]
One of the problems is that during generation the XmlElementAttribute `WGS84BoundingBox` is generated twice in `DatasetDescriptionSummaryBaseType.cs`.

The other problem is the `[System.ComponentModel.DefaultValueAttribute]` which I'd like to have configurable.

**Comment by mganss** [comment]
I've released 2.0.494 which fixes the issue with `DefaultValueAttribute` on `xml:lang`. I can now compile and deserialize when using `-r` and `-t-`.

**Comment by frankhommers** [comment]
Awesome! I'll check it out!

**Comment by frankhommers** [comment]
Yes this works.  Thanks!

But I got a new problem I think, I guess I need to open a new issue for this.
