### ISSUE TITLE
Add JsonIgnore attribute in addition to XmlIgnoreAttribute

### ISSUE THREAD

**Issue by metareven** [mganss/XmlSchemaClassGenerator#248]
Hi!

I am currently using this product to generate data-classes from our XSDs.
However when our webservers serialize this to json later on, we do not want to expose these "blablablaSpecified" attributes.
I see that these attributes are annotated with a XmlIgnoreAttribute, but not with a JsonIgnore for the same functionality when parsing to json.

Could you add functionality to add these JsonIgnore attributes all places where there is an XmlIgnoreAttribute, or at least add this as a cli-option?

**Comment by mganss** [comment]
You can use the `MemberVisitor` facility to customize generation. Here's a .NET script that replaces `xscgen` and adds a `JsonIgnore` attribute to all members that have the `XmlIgnore` attribute:

```c#
#! "net5.0"
#r "nuget: XmlSchemaClassGenerator-beta, 2.0.495"

using System.CodeDom;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;
using XmlSchemaClassGenerator;

var generator = new Generator
{
    OutputFolder = ".",
    CollectionType = typeof(List<>),
    GenerateNullables = true,
    Log = s => Console.WriteLine($"Generated {s}")
};

generator.MemberVisitor = (member, prop) =>
{
    if (member.CustomAttributes
        .OfType<CodeAttributeDeclaration>()
        .Any(a => a.AttributeType.BaseType == "System.Xml.Serialization.XmlIgnoreAttribute"))
    {
        member.CustomAttributes.Add(new CodeAttributeDeclaration(new CodeTypeReference(typeof(JsonIgnoreAttribute))));
    }
};

generator.Generate(Args);
```
