### ISSUE TITLE
Possibility to disable emit of GeneratedCodeAttribute on every class

### ISSUE THREAD

**Issue by TFTomSun** [mganss/XmlSchemaClassGenerator#254]
Having the version of the generator once on top of the file should be sufficient. If its emitted everywhere, it's imposible to detect the real changes from one to the next version. This is how it looks like when you compare 2 versions. All changes (red bars on the left) are just the version differences.
![image](https://user-images.githubusercontent.com/5387192/111040917-dfee4680-8435-11eb-976d-7bc6f902629f.png)

Is there a possibility to disable emitting the GeneratedCodeAttribute or the version info in it?

**Comment by mganss** [comment]
Currently, no. I'll add an option to disable generation of this attribute. Perhaps you can work around this issue by removing these lines before comparing (`grep -v GeneratedCodeAttribute ...`).

**Comment by mganss** [comment]
I've added option `--generatedCodeAttribute` in 2.0.513. If you disable this (`-gc-`) version information will be omitted from `GeneratedCodeAttribute` and the comment above the namespace.
