### ISSUE TITLE
'xscgen' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by sonudavidson** [mganss/XmlSchemaClassGenerator#256]
I'm using the dotnet-xscgen add-on to create .cs files from xsd files in my project. My project file looks like the following
`<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    
    <Exec Command="dotnet tool list -g" />
    <Exec Command="dotnet tool install -g dotnet-xscgen --version 2.0.425" IgnoreExitCode="true" />

    <Delete Files="Generated/*.cs" />

    <exec command="xscgen -n =$(rootnamespace) xsd/Blabla.xsd" ignoreexitcode="true" />
    <move sourcefiles="$(rootnamespace).cs" destinationfiles="Blabla.cs" />
    <move sourcefiles="Blabla.cs" destinationfolder="Generated" />
  </Target>`.
Sometimes I get the error that xscgen is not recognized and quite strangely this happens only in the build machines and I don't know why.

Here is the full log

`[exec]   dotnet tool list -g
[exec]   Package Id           Version      Commands         
[exec]   ---------------------------------------------------
[exec]   dotnet-svcutil       2.0.1        dotnet-svcutil   
[exec]   dotnet-xscgen        2.0.267      xscgen           
[exec]   gitversion.tool      5.3.7        dotnet-gitversion
[exec]   dotnet tool install -g dotnet-xscgen --version 2.0.425
[exec]   Tool 'dotnet-xscgen' is already installed.
[exec]   The command "dotnet tool install -g dotnet-xscgen --version 2.0.425" exited with code 1.
[exec]   xscgen -n =Com.BLABLA.Definitions xsd/PlcDeregisterPackage.xsd
[exec]   'xscgen' is not recognized as an internal or external command,
[exec]   operable program or batch file.`

It's a bit frustrating to know why this error occurs sometimes?

Any help is highly appreciated.

**Comment by mganss** [comment]
I have no idea what might be going on there. It seems xscgen is already installed as a global tool. Perhaps although it is installed it is not accessible through the PATH environment variable. Try logging the contents of PATH before you invoke xscgen. Also perhaps try making sure xscgen is freshly re-installed during the build by uninstalling, then installing again (or better yet, using xscgen as a local tool).
Even if it worked I think you would still be using version 2.0.267 with this setup because the call to `dotnet tool install` fails. Perhaps you should do `dotnet tool update -g --version 2.0.425`. Is there a reason why you need to use a specific version?
As you are using xscgen as part of your build process, perhaps it would be better to use xscgen as a local tool.

**Comment by mbaneryd** [comment]
I have a similar problem
```console
$ dotnet xscgen
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-xscgen does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

```console
$ dotnet tool list -g
Package Id         Version         Commands
------------------------------------------------
dotnet-ef          5.0.5           dotnet-ef
dotnet-format      5.0.211103      dotnet-format
dotnet-xscgen      2.0.521         xscgen
```

The tool has been installed in the global tool folder
```console
$ ls

    Directory: C:\Users\..\.dotnet\tools

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          2021-05-26    20:19                .store
-a---          2021-03-11    18:35         184712 dotnet-ef.exe
-a---          2021-05-26    20:19         128000 xscgen.exe
```

If I rename xscgen.exe to dotnet-xscgen.exe then it works as expected
Then I can run
````console
$  dotnet xscgen
Usage: dotnet xscgen [OPTIONS]+ xsdFile...
Generate C# classes from XML Schema files.
Version 2.0.521.0
xsdFiles may contain globs, e.g. "content\{schema,xsd}\**\*.xsd", and URLs.
Append - to option to disable it, e.g. --interface-.
```

**Comment by mganss** [comment]
@mbaneryd You can call `xscgen` without the `dotnet` prefix.

**Comment by mbaneryd** [comment]
> @mbaneryd You can call `xscgen` without the `dotnet` prefix.

Ok 👍🏼 

The documentation in Readme says that you should call it using `dotnet` prefix
https://github.com/mganss/XmlSchemaClassGenerator/blob/master/README.md#usage

**Comment by mganss** [comment]
@mbaneryd You're right. Fixed.
