### ISSUE TITLE
xsd:duration

### ISSUE THREAD

**Issue by bajker-sl** [mganss/XmlSchemaClassGenerator#258]
Hi,
XSD has a type **xsd:duration**. Information about this type is here:  https://www.w3.org/TR/xmlschema-2/#duration.
XmlSchemaClassGenerator generates string for it.
The expectation is that TimeSpan will be generated for it in C#.

**Comment by mganss** [comment]
Done in 2.0.521.

**Comment by bajker-sl** [comment]
Vielen Dank! Funktioniert wunderbar!
