### ISSUE TITLE
TimeSpan

### ISSUE THREAD

**Issue by bajker-sl** [mganss/XmlSchemaClassGenerator#259]
Hi. It is a continuation of the issue [#258](https://github.com/mganss/XmlSchemaClassGenerator/issues/258).

The XmlSerialiser can not work directly with TimeSpan. Unfortunally, an additional property is needed.
A similar question: https://stackoverflow.com/questions/637933/how-to-serialize-a-timespan-to-xml

This is the code generated now:

```
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("WaitTime")]
        public System.TimeSpan WaitTime { get; set; }
```

And so should it be so that XmlSerializer can deserialize it.

```
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.TimeSpan WaitTime
        {
            get => ts;
            set { ts = value; }
        }

        private TimeSpan ts;

        // Pretend property for serialization
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("WaitTime", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WaitTimeConverter
        {
            get => System.Xml.XmlConvert.ToString(ts);
            set { ts = System.Xml.XmlConvert.ToTimeSpan(value); }
        }
```

Can you do it this way?
If it is not possible then make again string instead of TimeSpan please. Because duration from xml can not be deserialized with current version.

Thanks.

**Comment by mganss** [comment]
It works in .NET Core but doesn't in .NET Framework 🙄 I think it's best to make this configurable.

**Comment by mganss** [comment]
There's now a `--netCore` command line option in 2.0.522.
