### ISSUE TITLE
xsd:nonNegativeInteger

### ISSUE THREAD

**Issue by bajker-sl** [mganss/XmlSchemaClassGenerator#261]
XSD has a type [xsd:nonNegativeInteger](https://www.w3.org/TR/xmlschema-2/#nonNegativeInteger).
Expected in C#: int.
XmlSchemaClassGenerator generates string.

**Comment by mganss** [comment]
XSD integers can exceed the range of C# ints which  is why in these cases XmlSchemaClassGenerator generates strings. You can specify `--fb -i int`  to override this (or just `-i int` if you want to use int for all integer derived types).

**Comment by bajker-sl** [comment]
Aha. Thank you. Wer lesen kann, ist klar im Vorteil :)
