### ISSUE TITLE
XmlSchemaException when trying to use my XSD

### ISSUE THREAD

**Issue by LokiMidgard** [mganss/XmlSchemaClassGenerator#27]
Hi, I just tried your tool but I have some odd behavior.

I try to create code from [this](https://nota-game.azurewebsites.net/schema/nota.xsd) xsd.

But this fails with:

```
Unbehandelte Ausnahme: System.Xml.Schema.XmlSchemaException: Die Identitätseinschränkung 'http://nota-game.azurewebsites.net/schema/nota:BesonderheitPK' wurde bereits deklariert.
   bei System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   bei System.Xml.Schema.BaseProcessor.SendValidationEvent(XmlSchemaException e, XmlSeverityType severity)
   bei System.Xml.Schema.Preprocessor.PreprocessIdentityConstraint(XmlSchemaIdentityConstraint constraint)
   bei System.Xml.Schema.Preprocessor.PreprocessElementContent(XmlSchemaElement element)
   bei System.Xml.Schema.Preprocessor.PreprocessElement(XmlSchemaElement element)
   bei System.Xml.Schema.Preprocessor.Preprocess(XmlSchema schema, String targetNamespace, ArrayList imports)
   bei System.Xml.Schema.Preprocessor.Execute(XmlSchema schema, String targetNamespace, Boolean loadExternals)
   bei System.Xml.Schema.XmlSchemaSet.PreprocessSchema(XmlSchema& schema, String targetNamespace)
   bei System.Xml.Schema.XmlSchemaSet.Add(String targetNamespace, XmlSchema schema)
   bei System.Xml.Schema.XmlSchemaSet.Add(XmlSchema schema)
   bei XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files) in C:\Users\patri\Source\Repos\XmlSchemaClassGenerator\XmlSchemaClassGenerator\Generator.cs:Zeile 185.
   bei XmlSchemaClassGenerator.Console.Program.Main(String[] args) in C:\Users\patri\Source\Repos\XmlSchemaClassGenerator\XmlSchemaClassGenerator.Console\Program.cs:Zeile 133.
```

I thought that the tool maybe mix up my local copy of the xsd and also importing it from the website, because it has a schemalocation.  So I modified the code that it also can use URLs additionally to files. And well it helped, code generation worked. But then I testet the "fix" on the console the exception was there again.

It works most of the time with the debugger attached, but running from command line always results in the exception.

Maybe it has something todo with a circular dependency of the xsd files. I think this was the reasen the xsd.exe got a stackoverflowexception.

**Comment by LokiMidgard** [comment]
Ok, I now have a state where it actually works.

I added follwing line bevor the Schemas are added to the XmlSchemaSet ```Set```. Line 182 in Generator.cs

```
Set.ValidationEventHandler += (s, e) => { Trace.TraceError(e.Message); };
```

I'm not 100% sure if this is actually a fix for the behavior I have. It wasn't 100% reproducable before. It could just be a race condition that now happens less often in my case.

**Comment by mganss** [comment]
The schema files aktionen.xsd and ausstattung.xsd have invalid schemaLocations in them, e.g. `http://nota-game.azurewebsites.net/schema/../talent.xsd`. If you download all files and adjust the schemaLocations to point to the local files, it works. You can validate the schema by loading it into Visual Studio, and viewing the error list (you have to check "Automatically download DTDs and schemas" in Options -> Text Editor -> XML -> Miscellaneous).

**Comment by LokiMidgard** [comment]
Thank you.

After activating this option in VS I got the same error there. I will try to get rid of it by eliminating the circular references.

**Comment by LokiMidgard** [comment]
Removing the circular references fixed it. Still interesting that sometimes it worked when started from visual studio.
