### ISSUE TITLE
Refactor console argument parsing to use System.CommandLine or similar

### ISSUE THREAD

**Issue by mahardan-oup** [mganss/XmlSchemaClassGenerator#274]
Hi, just found this project after worked on exactly the same thing for a couple of days :-)
I wondered if the console argument parsing in _XmlSchemaClassGenerator.Console\program.cs_ could be refactored to use a library built for that purpose? I have had great success with [System.CommandLine](https://github.com/dotnet/command-line-api) for example recently.

**Comment by mganss** [comment]
It already does: [Mono.Options](https://www.nuget.org/packages/Mono.Options/)

**Comment by mahardan-oup** [comment]
Ah. My apologies. I didn't recognise it.
Closing.
