### ISSUE TITLE
Ambiguous generated types

### ISSUE THREAD

**Issue by linxcrew** [mganss/XmlSchemaClassGenerator#276]
Hello, I am trying to generate c# classes from XSDs, where some XSDs use same names for different types (but in different namespaces). Unfortunately, I am not able to figure out how to generate different names or at least different namespaces, using XmlSchemaClassGenerator. You may test it using following command:

`XmlSchemaClassGenerator https://www.stormware.cz/xml/schema/version_2/data.xsd`

Also, there are all schemas available for download here: https://www.stormware.cz/xml/schema/all_schema_ver2.zip

The "main" (root) schema is "data.xsd"

There is for instance type "PeriodType" defined in different namespace and when I generate classes from MS's xsd.exe tool, the name for one of those enums is changed to PeriodType1 but in XmlSchemaClassGenerator the name keeps same, so it becomes ambiguous. Is there a way to force the tool to change ambiguous type names?

**Comment by mganss** [comment]
Yes, check out the `-n` option described here: https://github.com/mganss/XmlSchemaClassGenerator#mapping-xsd-files-to-c-namespaces
The most straightforward option is to define an individual C# namespace for each XML Schema namespace (`-n XMLNamespoace=CSNamespace`). Additionally, you can map individual XSD files to C# namespaces, but you should only consider this route if the mapping of XML namespaces is insufficient for your use case.

**Comment by linxcrew** [comment]
Thank you - that was it!
