### ISSUE TITLE
How to set different names for properties with the same qualified name in different classes?

### ISSUE THREAD

**Issue by aparshin** [mganss/XmlSchemaClassGenerator#293]
We have an XSD with multiple type elements with the same attributes, for example:

```xml
<xs:element name="First">
    <xs:complexType>
        <xs:attribute name="A"/>
        <xs:attribute name="B"/>
    </xs:complexType>
</xs:element>
<xs:element name="Second">
    <xs:complexType>
        <xs:attribute name="A"/>
        <xs:attribute name="B"/>
    </xs:complexType>
</xs:element>
```

We want to rename properties of generated classes, but use different names for different classes, e.g. `First.A` -> `First.Alpha`, but `Second.A` -> `Second.PropA`.

`NamingProvider` doesn't work in this situation because the property names (`A`, `B`, etc.) are the same. We tried to change the `Name` property inside `MemberVisitor`, but it doesn't work properly because the visitor is called _after_ some internal code is already generated (e.g. `*Specified` properties for collections used original `Name` before it is changed by `MemberVisitor`).

Is there any way to implement such "context-based" renaming?

**Comment by mganss** [comment]
I guess the `NamingProvider` is the right place to do this. We could extend it and pass more context to its methods. Unfortunately, `INamingProvider` is pretty messy with the properly named method `PropertyNameFromElement` which doesn't get called, though. Instead, the confusingly named `ElementNameFromQualifiedName` gets called in the regular case for generating a property name. Should we additionally pass the `TypeModel` to all of the methods that currently just take an `XmlQualifiedName`?

**Comment by aparshin** [comment]
@mganss Thank you for your reply! Yes, looks like `TypeModel` in addition to `XmlQualifiedName` will help in all situations similar to our case. Let me know if I can help somehow with this improvement!

**Comment by mganss** [comment]
@aparshin Could you create a PR? Thanks in advance.

**Comment by aparshin** [comment]
@mganss I looked at the sources and realized that `TypeModel` is not always available in all the places where `NamingProvider` is used. Also, `TypeModel`-based context doesn't cover situations when you use element-specific context for naming (e.g. `xs:annotation` schema elements).

What do you think about adding raw schema XML elements at an additional parameter to `NamingProvider` methods? For example:
```c#
string EnumTypeNameFromQualifiedName(XmlQualifiedName qualifiedName, XmlSchemaSimpleType xmlSimpleType);
string AttributeNameFromQualifiedName(XmlQualifiedName qualifiedName, XmlSchemaAttribute xmlAttribute);
string ElementNameFromQualifiedName(XmlQualifiedName qualifiedName, XmlSchemaElement xmlElement);
```

**Comment by mganss** [comment]
@aparshin Yes, that sounds good.

**Comment by aparshin** [comment]
@mganss OK, I'll prepare a PR soon!
