### ISSUE TITLE
Can Interface generated in a separated namespace folder

### ISSUE THREAD

**Issue by iamzhaoxu** [mganss/XmlSchemaClassGenerator#296]
I try to create generate the interface by group and the interface file is generated as expected.
However when I try to use the command below
-n "|Implementation.xsd=XXX.Implementation" -n "|Interface.xsd=XXX.Interface" --nc --cn -sf  Implementation.xsd

The interfaces folder will be generated in XXX.Implementation folder. I will expect the interfaces files should be sitting in the XXX.Interface folder.

The use case for is I want to share the same interfaces between different implementations and different implementations will have their own folders.

Do you guys have any idea?

**Comment by mganss** [comment]
Fixed in 2.0.630.
