### ISSUE TITLE
give namespace via -n =Test not possible on macos zsh shell

### ISSUE THREAD

**Issue by Jan-Zimmermann** [mganss/XmlSchemaClassGenerator#297]
xscgen -n =Test ALEAUD01.xsd works with /bin/bash but not on zsh shell

Error: Unhandled exception. System.ArgumentException: XML and C# namespaces should be separated by '='

i tried many variants with " and ' but not with success.

It is possible to give an altenative switch for -n with an different syntax? or define $ for Empty namespace. DOnt know if that would work, i´m not an zsh expert, but i think the space is the problem.

**Comment by mganss** [comment]
It works for me using `xscgen -n "=Test" ...` with zsh (Linux, though). Using `xscgen -n =Test ...` I get `zsh: Test not found`.

**Comment by Jan-Zimmermann** [comment]
unbeliveable.. Sorry to waste your time. That works for me. Thank you! the trick is to put the " or ' after the space.

**Comment by mganss** [comment]
No worries. Glad it works for you now.
