### ISSUE TITLE
Invalid generated code - interface does not return matching type

### ISSUE THREAD

**Issue by Syssx** [mganss/XmlSchemaClassGenerator#305]
Hi, while generating classes from this XSD: http://www.isdoc.cz/6.0/xsd/isdoc-invoice-6.0.1.xsd with interface option enabled, an interface called ISignature gets created:
```C#
public partial interface ISignature
    {

        System.Xml.XmlElement Any
        {
            get;
            set;
        }
    }
```

This interface gets referenced in the Invoice class:
```C#
public partial class Invoice : ISignature
```

This is all fine, however this error occurs:
_'Invoice' does not implement interface member 'ISignature.Any'. 'Invoice.Any' cannot implement 'ISignature.Any' because it does not have the matching return type of 'XmlElement'._

And the "Any" element of Invoice class:
```C#
[System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Collections.ObjectModel.Collection<System.Xml.XmlElement> Any
        {
            get
            {
                return this._any;
            }
            private set
            {
                this._any = value;
            }
        }
```
Signature is a group in the XSD and its referenced in the Invoice element.

I have generated the code without interface generation and it works fine. However, I just wanted to ask if I'm doing something wrong, or if this is one of the exceptions where interface generation doesn't work.

**Comment by mganss** [comment]
This occurred if an element had `maxOccurs=1` in the group definition, and `maxOccurs>1` in the referencing element's definition. I've added code in 2.0.646 to promote the interface property to a collection in these cases (along with the corresponding properties in all other implementing classes).
