### ISSUE TITLE
Option that allows you not to skip redundant intermediate classes

### ISSUE THREAD

**Issue by bajker-sl** [mganss/XmlSchemaClassGenerator#313]
Hi,

in the issue #225 is said that the **skipping** of the redundant intermediate class that has just a single collection property but not have collection semantics **is a feature**. Can you make it please as option and not feature?

My problem:

There is a standard XSD for some timetables. Consider the following part of it:

![image](https://user-images.githubusercontent.com/82222243/159205851-c05676a9-7e64-4a37-90be-508be87e3753.png)

Generated class `Infrastructure` has Collection of ocps. Intermediate class `OperationControlPoints` was consider as redundant and was skipped,

Besides that there is a custom extension of this standard XSD:

![image](https://user-images.githubusercontent.com/82222243/159206866-56ab1357-4a44-4f70-9704-3e179d90f10a.png)

The class for `OcpCultureMappings` is generated but is not reachable because `OperationControlPoints` is skipped. Thus, `Infrastucure` has collection of ocps but no `OperationContolPoints`...

I tried to use option `--ef`. It helped for root elements but in the depth the problem stays.

I suppose if it was possible to switch off the skipping feature for root elements for option `--ef` than it can be possible to implement it for all elements for a new general option.

Thanks in advance.

**Comment by mganss** [comment]
Added option `--ar` in 2.0.660.

**Comment by bajker-sl** [comment]
Hi Michael,
unfortunerly, I don't see difference between --ar=false and --ar=true.

I expected
```
namespace RailML25Model.Rail
{
    ⁞
    public partial class Infrastructure : RailML25Model.Rail.TInfrastructure
    {        
        ⁞
        [System.Xml.Serialization.XmlElementAttribute("operationControlPoints")]
        public EOperationControlPoints OperationControlPoints { get; set; }
        ⁞
    }
}
```

but in both cases I get

```
namespace RailML25Model.Rail
{ 
    ⁞
    public partial class Infrastructure : RailML25Model.Rail.TInfrastructure
    {
        ⁞
        public Infrastructure()
        {
            ⁞
            this._operationControlPoints = new System.Collections.ObjectModel.Collection<EOcp>();
            ⁞
        }        
        ⁞    
        private System.Collections.ObjectModel.Collection<EOcp> _operationControlPoints;
        
        [System.Xml.Serialization.XmlArrayAttribute("operationControlPoints")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ocp", Namespace="https://www.railml.org/schemas/2021")]
        public System.Collections.ObjectModel.Collection<EOcp> OperationControlPoints
        {
            get
            {
                return this._operationControlPoints;
            }
            private set
            {
                this._operationControlPoints = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the OperationControlPoints collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperationControlPointsSpecified
        {
            get
            {
                return (this.OperationControlPoints.Count != 0);
            }
        }
        ⁞
    }
}
```

**Comment by mganss** [comment]
Try `--ar-`.

**Comment by bajker-sl** [comment]
so works. Thank you very much!!! 👍 👍 👍
