### ISSUE TITLE
doesn't work anymore for .NET4.8

### ISSUE THREAD

**Issue by bajker-sl** [mganss/XmlSchemaClassGenerator#316]
Hi Michael,

I have problem with this change https://github.com/mganss/XmlSchemaClassGenerator/commit/729c1b52fb8f321356ddd1a0f9535dd52ad8104f.

The generated code works for `net6` but not for `net48` and I need both.

The problem is that the property `ConvertValueInInvariantCulture` of `System.ComponentModel.DataAnnotations.RangeAttribute` is available in assembly `System.ComponentModel.Annotations` since version **4.2.0.0** (https://apisof.net/catalog/200f71c2-d949-ac7b-4a07-8b7351509f67?fx=net48).

But version **4.0.0.0** is used for `net48`. 

![image](https://user-images.githubusercontent.com/82222243/161772404-cbaafee4-1521-4f49-9edf-322ddfd9a545.png)

It leads to build errors.

![image](https://user-images.githubusercontent.com/82222243/161774716-136d8966-3db0-4473-bf4b-f1bcc1c9b517.png)

Can you add please a boolean option that make [this change](https://github.com/mganss/XmlSchemaClassGenerator/commit/729c1b52fb8f321356ddd1a0f9535dd52ad8104f) optional?

**Comment by mganss** [comment]
There already is, it's the `--nc`/`--netCore` option. In fact, this option is off by default so just leave it off  in order to not generate `ConvertValueInInvariantCulture`.

**Comment by bajker-sl** [comment]
Stimmt. I used `--nc` to generate `TimeSpan`. Then I leave it off and convert Timespan from string manually.
Thanks for help.
