### ISSUE TITLE
Not include LeftParenthesis or RightParenthesis in C# generated file 

### ISSUE THREAD

**Issue by kristian014** [mganss/XmlSchemaClassGenerator#319]
I generated a C# file from a XSD file. Any chance I could get it to generate the C# file without adding RightParenthesis or underscore to its value as shown in the picture below? 

![xsd](https://user-images.githubusercontent.com/61020712/165137278-aec9794b-ccbb-45e2-a707-81b61c52b57c.PNG)

Outcome -> Garden_LeftParenthesisDomesticRightParenthesis
Expected out -> GardenDomestic

**Comment by mganss** [comment]
Unfortunately, this is not easy using the current code. You could use the library to create C# from XSD and pass in a custom `NamingProvider`. Your custom naming provider would need to override all methods that call `NamingExtensions.ToTitleCase()`:
https://github.com/mganss/XmlSchemaClassGenerator/blob/4b89ec3c23c29b826d0e181c21bde301a45db106/XmlSchemaClassGenerator/NamingExtensions.cs#L101-L111
This calls `MakeValidIdentifier` where the invalid characters are replaced.

**Comment by kristian014** [comment]
Thanks
