### ISSUE TITLE
Add support for Nullable Reference Types (mainly `string`)

### ISSUE THREAD

**Issue by las-nsc** [mganss/XmlSchemaClassGenerator#328]
Please add a flag to enable NRT variables based on `optional|required`, particulary for strings, so that it plays nicely with modern code. Currenltly `string`s are lacking the nullable indicator (`?`) in the generated code so do not indicate that they need to be `null` checked when accessed.

It would be nice if there was also an option to exclude the `...Specified` properties for `Nullable<T>` (when using the `--nullable` switch) and NRTs.

Since the whole generated file will require `#nullable enable` it may be necessary to add ` = null!` initialisers on nullable properties so they don't cause warnings and rely on the schema validation and deserializer to make sure things that shouldn't be `null` are initialised. Alternatively `#nullable enable annotations` may be good enough.

**Comment by las-nsc** [comment]
Oh, great. Readme needs updating then. Thanks.

**Comment by mganss** [comment]
Done.

**Comment by mganss** [comment]
Fixed.
