### ISSUE TITLE
API out of sync with README

### ISSUE THREAD

**Issue by masaeedu** [mganss/XmlSchemaClassGenerator#33]
The README has a snippet referring to `GenerateNamespaceName` and `NamespaceMapping`, which I'm assuming are supposed to be used for mapping namespaces from the XML schema into namespaces in the generated C#. These properties no longer seem to be a part of the `Generator` class. Could the README be updated to show how to properly initialize a `Generator`?

**Comment by mganss** [comment]
Thanks for reporting this. I've updated the README.
