### ISSUE TITLE
How to generate XML having the XML schema generated.

### ISSUE THREAD

**Issue by ZaxonXP** [mganss/XmlSchemaClassGenerator#331]
Hi,

I am not C# expert yet, so I do not know how to use this generated class in order to produce XML file. 
I have other classes with the same property names as in the generated schema class, but I do not know how to use them.
Can you provide some examples?

Kind regards,
Piotr

**Comment by mganss** [comment]
The generated code is intended to be used with `XmlSerializer` provided by .NET. So all documentation for `XmlSerializer` applies to code generated by `XmlSchemaClassGenerator` as well. The class documentation for `XmlSerializer` has an examples section here: https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlserializer?view=net-6.0#examples
