### ISSUE TITLE
Nullable Reference Type attributes are always fully qualified

### ISSUE THREAD

**Issue by las-nsc** [mganss/XmlSchemaClassGenerator#333]
When using the flag `-cn` with `-nr` the added attributes ought to be short names, with a `using System.Diagnostics.CodeAnalysis;` added.

**Comment by las-nsc** [comment]
Having looked at the code, I understand this is because the attribute is `internal` within the .net runtime being used by the project. I guess you don't want to upgrade the .net version for just this reason...

**Comment by mganss** [comment]
Fixed through #336
