### ISSUE TITLE
Use simplified type names for basic types if `--compactTypeNames` is specified

### ISSUE THREAD

**Issue by las-nsc** [mganss/XmlSchemaClassGenerator#335]
Use `string` rather than `String`, `bool` rather than `Boolean` and `int` rather than `Int32` etc. 

It used to do this in a previous version, so should probably be default behaviour, and add a flag to use the more verbose names (if anyone actually wants it, not sure why you would...).

**Comment by las-nsc** [comment]
Having examined the code, I can't figure out why this is happening. It's up to `CSharpCodeProvider` to change basic types to their keywords, which must be the same, unless something is managing to break it.

**Comment by mganss** [comment]
This occurs if `--compactTypeNames` is specified. This results in the `System` namespace being added to the list of imported namespaces, causing `CsharpCodeProvider` to emit the longhand type names. I don't know how to prevent this 🤷🏻
