### ISSUE TITLE
.NET Standard support

### ISSUE THREAD

**Issue by masaeedu** [mganss/XmlSchemaClassGenerator#34]
The project currently targets .NET 4.5, making it difficult to use with .NET Standard class libraries. It would be good if this could be ported to a suitably low .NET Standard version.

**Comment by mganss** [comment]
I've started work on this in the `netstandard` branch. The lowest netstandard version that supports what we need is 2.0, particularly because of classes in the `System.Xml.Schema` namespace. I couldn't get the test project to build with netcoreapp2.0 so far because of dotnet/sdk#1241.

**Comment by mganss** [comment]
v2.0.73-beta supports netstandard2.0 now in addition to net45. The console application is available for netcoreapp2.0 and net45. The test project targets only net452 currently though because XmlSampleGenerator accesses private fields through reflection which are not there in .NET Core.

**Comment by masaeedu** [comment]
Awesome, thanks very much!
