### ISSUE TITLE
Type model name necessary for property names?

### ISSUE THREAD

**Issue by budul100** [mganss/XmlSchemaClassGenerator#356]
I was trying to convert the ["Infrastructure register scheme" of the European Railway Agency](https://www.era.europa.eu/sites/default/files/registers/docs/rinf_schema_en.xsd). The current naming leads to very long type model names (e.g. _RINFDataOperationalPointOPTrackOPTrackPlatformOPTrackPlatformIdentification_).

Apparently, this is controlled [by the naming provider](https://github.com/mganss/XmlSchemaClassGenerator/blob/c9268e6ae4c872d571e457de09b5a666fd1d4124/XmlSchemaClassGenerator/NamingProvider.cs#L23-L45). Now I was wondering whether it would be a helpful option to allow property names without the type model names. E.g. like this 

```cs
        /// <summary>
        /// Creates a name for a property from an attribute name
        /// </summary>
        /// <param name="typeModelName">Name of the typeModel</param>
        /// <param name="attributeName">Attribute name</param>
        /// <param name="attribute">Original XSD attribute</param>
        /// <returns>Name of the property</returns>
        public virtual string PropertyNameFromAttribute(string typeModelName, string attributeName, XmlSchemaAttribute attribute, bool namingOption)
        {
            return namingOption
                        ? typeModelName.ToTitleCase(_namingScheme) + attributeName.ToTitleCase(_namingScheme);            
                        : attributeName.ToTitleCase(_namingScheme);
        }

        /// <summary>
        /// Creates a name for a property from an element name
        /// </summary>
        /// <param name="typeModelName">Name of the typeModel</param>
        /// <param name="elementName">Element name</param>
        /// <param name="element">Original XSD element</param>
        /// <returns>Name of the property</returns>
        public virtual string PropertyNameFromElement(string typeModelName, string elementName, XmlSchemaElement element, bool namingOption)
        {
            return namingOption
                        ? elementName.ToTitleCase(_namingScheme) + attributeName.ToTitleCase(_namingScheme);            
                        : elementName.ToTitleCase(_namingScheme);
        }
```

Or do you see a better option to get a similar result?

**Comment by mganss** [comment]
The way it is done by default currently is to generate unique class names for types that are anonymous in the XSD. I'd rather not change this default behavior but you can override these methods in a custom `NamingProvider` and pass that to the `Generator`.

**Comment by budul100** [comment]
Thank you for your answer.
