### ISSUE TITLE
xs:time is serialized as string

### ISSUE THREAD

**Issue by AGranpreIntegrace** [mganss/XmlSchemaClassGenerator#37]
schema properties with datatype xs:time are serialized as string
xsd.exe serializes these properties as System.DateTime

would be nice to have an option to supply xs:time datatype the same way that integers are being handled.

**Comment by mganss** [comment]
IIRC this was done deliberately because of interoperability issues. But I agree that configurability would be a nice feature. Implementing this should be straightforward. I won't get to it before two weeks from now, though. But you're more than welcome to provide a PR :)
