### ISSUE TITLE
No XML 1.1 support

### ISSUE THREAD

**Issue by zooid** [mganss/XmlSchemaClassGenerator#371]
Is it possible to add XML 1.1 support?

**Comment by mganss** [comment]
I don't know. Serialization depends on XmlSerializer. Do you encounter errors? Can you provide an example?

**Comment by jzabroski** [comment]
This wonderful answer from Jon Skeet suggests as of 2018, XmlReader didn't support xml 1.1 https://stackoverflow.com/a/17279558/1040437

Would be trivial to verify.

**Comment by mganss** [comment]
Same output in net7.0, i.e. no support.

**Comment by jzabroski** [comment]
See also http://www.cafeconleche.org/books/effectivexml/chapters/03.html

**Comment by mganss** [comment]
I'm closing this as it seems XML 1.1 will be supported by .NET.
