### ISSUE TITLE
Handling invalid characters during serialization

### ISSUE THREAD

**Issue by korteksz** [mganss/XmlSchemaClassGenerator#373]
Hi,

I have an object (generated by this library) and one its fields contain invalid XML characters and when I call the XmlSerializer.Serialize it throws the respective exception. What I would like to achieve is to make the Serialize method safe so that I don't have to care about exception handling, so I would like to remove/replace those invalid characters before/during the serialization. 

I would like to ask if you know a solution for the above mentioned situation?

Thanks for your support,
korteksz

**Comment by mganss** [comment]
Can you provide a short example? What does the class definition look like and what is the property's value that causes the exception?

**Comment by korteksz** [comment]
So the concrete problem is that we generated a model based on this schema: 
https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd

We have an own test logger which fills this data based on the test results and sometimes when our tests are failing their output contains invalid xml characters and when we want to serialize out the filled data then the serialization fails because of the invalid character.

So a pseudo code is something like that: 

var testSuite = new Testsuite();
testSuite.TestCase[0].Failure.Message = "Text with invalid char \0";

var serializer = new XmlSerializer(typeof(Testsuite);
serializer.Serialize(testSuite); //here comes the exception

**Comment by mganss** [comment]
Try using an `XmlWriter` with `CheckCharacters` set to `false`:

```c#
using var writer = XmlWriter.Create(stream, new XmlWriterSettings { CheckCharacters = false });
```

**Comment by korteksz** [comment]
Oh, I haven't seen that possibility! Thank you very much for your help :)
