### ISSUE TITLE
One or more projects are incompatible with .NETCoreApp,Version=v2.0

### ISSUE THREAD

**Issue by scemis** [mganss/XmlSchemaClassGenerator#38]
When I try to open solution I get this error message, 
**"One or more projects are incompatible with .NETCoreApp,Version=v2.0"**
after that my VS 2017 Community is crashed.

**Comment by mganss** [comment]
I can't repro. A fresh clone opens, builds, and tests fine. It is true that the test project targets only net452 (see #34) but that shouldn't matter. In Visual Studio Installer, do you have ".NET desktop development" checked under "Workloads" and all the .NET Framework targeting packs and SDKs under "Individual components"?

**Comment by scemis** [comment]
Sorry for delay,

I was super busy.

You are right something wrong on my side. Today I tried on another computer
(Win 7 Pro 64 bit) with VS Enterprise 2017 15.3.3
almost all components installed (included xamarin) -> I have no problem.

Problem I have on another machine (Win 10 Pro 64 bit) with VS Community
2017 13.3.5, (xamarin not included) the rest is there.
I can load only Tests project, the rest 3 course the issue.

If you have any idea what could be the reason of my problem, please let me
know.

Thanks.

**Comment by twsouthwick** [comment]
I had a similar problem today and I fixed it by uninstalling some old .NET Core SDKs that I did not need anymore and installing the latest 2.1.0.300 SDK that was released today
