### ISSUE TITLE
Support Enums with different spelled values

### ISSUE THREAD

**Issue by relaxdays** [mganss/XmlSchemaClassGenerator#39]
The tool works great but has one little issue when it comes to enums with different spelled values (for example usefull for User-Inputs).
Example

```xml
<xsd:simpleType name="Gender">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="male"/>
		<xsd:enumeration value="female"/>
		<xsd:enumeration value="Male"/>
		<xsd:enumeration value="Female"/>
	</xsd:restriction>
</xsd:simpleType>
```

This lead to an not valid Enum, because the Member "Male" and "Female" would be generated twice.

**Comment by mganss** [comment]
Ideally, we would have a way of configuring/overriding the generated names of individual classes and members (like we already have for namespaces).

Currently, your only option (besides editing the generated files) is to use the direct naming scheme option which can be invoked with the `-a-` command line switch.

**Comment by relaxdays** [comment]
We created a PR for this which solve our issue + #35, please review :)
