### ISSUE TITLE
Command line arguments with default set to true/enabled cannot be set to false

### ISSUE THREAD

**Issue by MaceWindu** [mganss/XmlSchemaClassGenerator#396]
debuggerStepThrough  option has defaults set to `true` and doesn't accept any arguments, so it is not possible to set it to `false` from command line

**Comment by mganss** [comment]
Use `--dst-` (note the minus sign at the end). See command line options documentation here: https://github.com/xamarin/XamarinComponents/blob/main/XPlat/Mono.Options/GettingStarted.md
