### ISSUE TITLE
Duplicate XmlElementAttribute

### ISSUE THREAD

**Issue by panost** [mganss/XmlSchemaClassGenerator#401]
Using the classes generated from this xsd ([Sql Server 2019 Show Plan Xml ](https://schemas.microsoft.com/sqlserver/2004/07/showplan/sql2019/showplanxml.xsd)) using the XmlSerializer 

```csharp
public static class ShowPlanUtil {
    private static XmlSerializer _lizer = XmlSerializer.FromTypes( new[] { typeof( ShowPlanXML ) } )[ 0 ];
    public static ShowPlanXML Load(Stream stream) {
        return (ShowPlanXML)_lizer.Deserialize( stream );
    }
}
```

I get two exceptions
First
System.InvalidOperationException: 'The XML element 'ScalarOperator' from namespace 'http://schemas.microsoft.com/sqlserver/2004/07/showplan' is already present in the current scope. Use XML attributes to specify another XML name or namespace for the element.'

which I have to alter the class `AssignType` and delete the property
```csharp
public ScalarType ScalarOperator1 { get; set; }
```

and after I fix this, the second is
System.InvalidOperationException: 'The XML element 'ColumnReference' from namespace 'http://schemas.microsoft.com/sqlserver/2004/07/showplan' is already present in the current scope. Use XML attributes to specify another XML name or namespace for the element.'

which I have to go to the class `DefinedValuesListTypeDefinedValue`  and delete the property `ColumnReference1`, field `_columnReference1` and the `ColumnReference1Specified` property

Probably deleting them was not the right approach ?

**Comment by mganss** [comment]
I can't download the schema, I keep getting "the request is blocked" 🤷🏻 Can you attach it here?

Have you tried the `--sg` option?

**Comment by panost** [comment]
How about [this url](https://schemasmicrosoft.azurewebsites.net/sqlserver/2004/07/showplan/sql2019/showplanxml.xsd) or the 2019 option [from here](https://schemasmicrosoft.azurewebsites.net/sqlserver/2004/07/showplan/)
Also attached a compressed copy of the same 
[ShowPlanXml-2019.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/12105888/ShowPlanXml-2019.zip)

Also the **SeparateSubstitutes** option does nothing

```csharp
[System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "1.0.0.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute("AssignType", Namespace="http://schemas.microsoft.com/sqlserver/2004/07/showplan")]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class AssignType
{
	
	[System.Xml.Serialization.XmlElementAttribute("ColumnReference")]
	public ColumnReferenceType ColumnReference { get; set; }
	
	[System.Xml.Serialization.XmlElementAttribute("ScalarOperator")]
	public ScalarType ScalarOperator { get; set; }
	
	[System.ComponentModel.DataAnnotations.RequiredAttribute()]
	[System.Xml.Serialization.XmlElementAttribute("ScalarOperator")]
	public ScalarType ScalarOperator1 { get; set; }
```

generates two elements with the same XmlElementAttribute

**Comment by mganss** [comment]
The problem is that there are duplicate elements with the same name and type in the schema where one of them is inside a choice:

```xsd
<xsd:complexType name="AssignType">
        <xsd:sequence>
	        <xsd:choice>
		        <xsd:element name="ColumnReference" type="shp:ColumnReferenceType" />
		        <xsd:element name="ScalarOperator" type="shp:ScalarType" />
	        </xsd:choice>
	        <xsd:element name="ScalarOperator" type="shp:ScalarType" />
	        <xsd:element name="SourceColumn" type="shp:ColumnReferenceType" minOccurs="0" maxOccurs="unbounded" />
	        <xsd:element name="TargetColumn" type="shp:ColumnReferenceType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
</xsd:complexType>
```

I've added code to just swallow the duplicate elements and always generate a collection in these cases. Please check if this satisfies your use case. The version is 2.0.862-beta.

**Comment by panost** [comment]
It works, I am not sure that a collection is the right choice here or to just return the property found (merge the two elements in one property). Commenting the line #947
```csharp
property.IsCollection = true;
```
still works, but I do not have the expertise to know if this is a generic solution or just works for my schema and data

Anyway, the issue is resolved for me. Thank you very much!

**Comment by mganss** [comment]
According to the schema, there can be two consecutive `ScalarOperator` elements so there needs to be a collection AFAICT.
