### ISSUE TITLE
Please simplify the -n option

### ISSUE THREAD

**Issue by a-einstein** [mganss/XmlSchemaClassGenerator#408]
I got quite frustrated with the -n option on Windows. 

I just wanted to do the basic thing, indicate the target namespace. 

With xsd.exe that is just
`/n:<namespace>`

Here, after a lot of failed attempts, I had to read an issue to try the thing that worked for me: 
`-n "=<namespace>"`

Unless I misundertood, it seems overly complicated now, with options one does not inmediately need.
I would suggest just something like
`-n <namespace>`

Or at least clarify the help text.

Thanks.

**Comment by mganss** [comment]
The relevant documentation is in the README: https://github.com/mganss/XmlSchemaClassGenerator#mapping-empty-xml-namespaces

Your example is for the empty namespace. Unlike xsd.exe, XmlSchemaClassGenerator can map XML namespaces to C# namespaces.

But I agree that the current syntax might be too complicated for simple use cases. Perhaps we should allow specifying a single C# namespace for all XML namespaces (not only the empty XML namespace) using `-n Example`?
