### ISSUE TITLE
Output file selection does not work.

### ISSUE THREAD

**Issue by Gjoll** [mganss/XmlSchemaClassGenerator#43]
Selecting the output file by using the '|' char after the xml schema name does not appear to work.

The current code causes a Namespacekey to be added to the NamespaceProvider.InternalDictionary dictionary with the source field set to the file name. (see line 92 of console program.cs).

When Generator.BuildNamespace is called, the source field of the  NamespaceKey is set to the Uri of the source xsd file, and NamespaceProvider.FindNamespace fails to find a match. (see line 235 of Generator.cs)

The following are the command line args I used to get this error.
XmlSchemaClassGenerator ElmSchemaSource\Types.xsd -o=ElmSchemaGenerated -n="urn:hl7-org:elm-types:r1|Types.cs"="Applicadia2.Import.CQL.ElmModel"

**Comment by mganss** [comment]
The pipe option is not meant to map namespaces to output files but rather combinations of XML Schema namespaces and *input* file names to C# namespaces. Mapping to specific output file names is not currently supported.

**Comment by Gjoll** [comment]
Ok. Guess I misunderstood the docs. Thanks for the feedback. BTW: Nice tool, thanks for your work.
