### ISSUE TITLE
MaxLengthAttribute not generated for some elements

### ISSUE THREAD

**Issue by bmmartinn** [mganss/XmlSchemaClassGenerator#431]
Hello! Thanks for an amazing tool!
I'm having some troubles with `MaxLengthAttributes` not being generated for some elements. 
It happens to elements defined as followed in the schema file:
```xsd
<xs:element name="TelephoneNumber" type="Telephone" minOccurs="0">
	<xs:annotation>
		<xs:documentation>Telephone number</xs:documentation>
	</xs:annotation>
</xs:element>

<xs:simpleType name="Telephone">
	<xs:annotation>
		<xs:documentation>Simple type Telephone</xs:documentation>
	</xs:annotation>
	<xs:restriction base="String20"/>
</xs:simpleType>

<xs:simpleType name="String20">
	<xs:restriction base="xs:string">
		<xs:minLength value="0"/>
		<xs:maxLength value="20"/>
	</xs:restriction>
</xs:simpleType>
``` 

It works fine for elements with a type that doesn't have a base reference in the restriction to another simple type. 
In this case, it works as expected if the `TelephoneNumber` element have the type `String20`.

Should this work? Or is it rather a weird structure in the schema file?

**Comment by mganss** [comment]
Fixed in 2.1.954.
