### ISSUE TITLE
Using underscores while generating C# namespace from XSD namespace

### ISSUE THREAD

**Issue by ploef** [mganss/XmlSchemaClassGenerator#433]
Hi,

Our xsd namespaces contain a version number (eg. v3.0). That version number is not included in the generated C# namespace and I understand why. But I think it should be possible to use underscores, but they are ignored also.

A C# namespace can include namespaces I think. Would it be possible to make it so that
http://myschema/v3_0_1/test is translated in a C# namespace like MySchema.v3_0_1.test when using XMLNamespace=CSNamespace

**Comment by mganss** [comment]
The automatic C# namespace name generation isn't very advanced. It's best to provide an explicit mapping through `-n` or `--nf` as described here: https://github.com/mganss/XmlSchemaClassGenerator#mapping-xsd-files-to-c-namespaces
