### ISSUE TITLE
Inherited classes is generated with a bad namespace

### ISSUE THREAD

**Issue by frankhaugen** [mganss/XmlSchemaClassGenerator#434]
I'm looking to use this library for my UBL library, and I disappointed to see that inheritance isn't handled. As you can see the namespace is rendered with a `:` instead of an `_`, same goes for the `-2` in the namespace statement.

The XSDs are UBL2s which is an international standard for commerce, an I would recommend that you use it in your tests, as its a very common use-case to generate types from UBLs, (I work in financial software development in my day job)

Output:
```csharp
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.956.0
namespace urn_oasis_names_specification_ubl_schema_xsd_CommonBasicComponents-2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.956.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccountFormatCodeType", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AccountFormatCode", Namespace="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2")]
    public partial class AccountFormatCodeType : urn:oasis:names:specification:ubl:schema:xsd:UnqualifiedDataTypes-2.CodeType
    {
    }
}
```

XSD Sources: [https://github.com/frankhaugen/Frank.Libraries/tree/05742727cf16e9b7761ff459e02f6e4c6debecf0/src/Frank.Libraries.Ubl/Frank.Libraries.Ubl/xsd](url)

My code, (a LinqPad 7 script):
```csharp
var inputFolder = @"D:\repos\Frank.Libraries\src\Frank.Libraries.Ubl\Frank.Libraries.Ubl\xsd";
var outputFolder = "D:/temp/generated";

var files = new List<string>();

var generator = new Generator
{
	OutputFolder = outputFolder,
	Log = s => files.Add(s),
	GenerateNullables = true,
	SeparateNamespaceHierarchy = true,
	CollectionImplementationType = typeof(List<>),
	NamespaceProvider = new NamespaceProvider()
	{
		GenerateNamespace = x => x.XmlSchemaNamespace
	},
};

var directory = new DirectoryInfo(inputFolder);

generator.Generate(directory.EnumerateFiles("*.xsd", SearchOption.AllDirectories).Select(x => x.FullName));

var fileInfos = files.Select(x => new FileInfo(x)).OrderBy(x => x.Name);

var content = new StringBuilder();
foreach (var fileInfo in fileInfos)
{
	content.AppendLine(File.ReadAllText(fileInfo.FullName));
}
var outFile = Path.Combine(outputFolder, "Output.cs");

File.WriteAllText(outFile, content.ToString());
```

**Comment by mganss** [comment]
You must provide your own mapping from XML namespace names to C# namespace names through the `GenerateNamespace` func. The default namespace provider can handle just basic cases. If, like in your example above, you try to set the C# namespace to the same value as the XML namespace, it will be passed as-is to the `CodeDom` provider. I'm even surprised that it replaces `:` with `_`.

Assuming all the namespaces in your use case look similar to the above example, then this should suffice:

```c#
GenerateNamespace => n => n.XmlSchemaNamespace.Replace(":", "_").Replace("-", "_")
```

**Comment by frankhaugen** [comment]
> ...I'm even surprised that it replaces `:` with `_`...
That's why I assumed it was a bug since it "almost" got it right by default, as if it was supposed to replace with underscores.

Thank you for your prompt reply, (I had already experimented myself into replacing all namespaces with a generic one), essentially fixing the issue. Keep up the great work!
