### ISSUE TITLE
Support 'init' setter mode for collectionSettersMode

### ISSUE THREAD

**Issue by strigefleur** [mganss/XmlSchemaClassGenerator#456]
Generated collection models by default have `private` setters effectively blocking it from being serialized by defaut .net `System.Json`. Per docs one could use `public` setter instead of `private` but this way it's obviously less safe.

What could be the easiest solution is to allow new option to generate `init` setters that both safe and serializable.

`--collectionSettersMode=Init`

```cs
        public Collection<SomeClass> SomeProp
        {
            get
            {
                return _someProp;
            }
            // private set
            init
            {
                _someProp = value;
            }
        }
```

**Comment by mganss** [comment]
Added in 2.1.1051.

**Comment by strigefleur** [comment]
There has to be a regression since: no constructor is generated when using new "Init" option. I guess it could be not the only related issue but the very first I noticed so far.

**Comment by mganss** [comment]
Perhaps we should add another option `InitWithoutConstructorInitialization` similar to `PublicWithoutConstructorInitialization`?
Also, in the `Init` case, should we add `required`?

**Comment by strigefleur** [comment]
`InitWithoutConstructorInitialization` sounds nice - it makes the model open for some factory initializers.

However I'm not sure about making those `required` - it would enforce restriction though we don't know actual properties purposes - one could split initialization into multiple parts for example.

**Comment by mganss** [comment]
OK I've added it in 2.1.1057.
