### ISSUE TITLE
Support generation of Nullable ValueTypes

### ISSUE THREAD

**Issue by fgheysels** [mganss/XmlSchemaClassGenerator#464]
It would be nice if would be possible if nullable-value types could be generated for simple-Type properties that are defined as 'not mandatory' (minOccurs=0) in the XSD.

**Comment by mganss** [comment]
The `-0` /`--nullable` option does that. Or do you mean something else?

**Comment by fgheysels** [comment]
I must have missed that one.  Seems indeed that this is doing what I expected.

However, I can see that the `xxxSpecified` properties are also generated as a get/set property.
Wouldn't it be an idea that these properties are -in this case?- generated as read-only / get only properties and return true when the corresponding property is not null ?

**Comment by mganss** [comment]
The nullable property serves as an adapter to the pair of `Value` and `Specified` properties. It holds no state of its own.

**Comment by fgheysels** [comment]
I'm not sure what you mean with your last comment ?

When using the `-0` together with the `--useShouldSerialize` arguments, a class is generated that contains for instance this:

```csharp
public System.Nullable<System.DateTime> DeclarationDate { get; set; }

public virtual bool ShouldSerializeDeclarationDate()
{
    return DeclarationDate.HasValue;
}
```

This actually does exactly what I was looking for.

**Comment by mganss** [comment]
> I'm not sure what you mean with your last comment ?

If I understood you correctly, you were proposing to make the `Specified` properties get-only and serve as an adapter to the nullable properties (which would then hold the actual state). The current implementation works the other way round, i.e. the nullable properties hold no state of their own and merely serve as adapters to the pair of `Value` and `Specified` which hold the actual state.

Glad the `ShouldSerialize` pattern works for your use case 😄
