### ISSUE TITLE
time with Time Zone Indicator

### ISSUE THREAD

**Issue by bajker-sl** [mganss/XmlSchemaClassGenerator#473]
Hi, we get xml files with attributes 'Arrival' and 'Departure' that have type `time`.

According properties in the generated C# model have type `DateTime`.

Our problem is that following two time values with `TimeZoneIndicator` `"01:30:00+10:00"` and `"17:30:00+02:00"` are deserialzed to the same DateTime value `01.01.0001 16:30:00` local time (Berlin).
But in fact there are **24 hours** between these time values.

Thus, if we have DateTime `01.01.0001 16:30:00` then we don't know whether this is time of **current day** (case "17:30:00+02:00") or of **day before** (case "01:30:00+10:00").

Do you have any idea, suggestion, recommendation?
The only idea that I have is to generate `string` from `xs:time`. Then we could combine this deserialized string with date in C# and parse it together to correct `DateTime` with method `DateTime.Parse`.

**Comment by bajker-sl** [comment]
Small test for better understanding. `time1` and `time2` for deserialzed values, `time3` and `time4` combined with some date.

![image](https://github.com/mganss/XmlSchemaClassGenerator/assets/82222243/5549e09f-1e29-4ae2-bd9b-9e265fd20922)

**Comment by mganss** [comment]
I'm not sure I understand. The `xs:time` value that's in the XML doesn't carry any date information does it? So the date portion of the deserialized `DateTime` should be irrelevant.

**Comment by bajker-sl** [comment]
Yes, `xs:time` has only time, no date. It is correct. For general case when `xs:time` is without Time Zone Indicator, the date portion of the deserialized `DateTime` is indeed irrelevant.
`"01:30:00"` is deserialized to `1.01.0001 1:30`, `DateTimeKind` is Unspecified. Everything is fine.

But `xs:time` can look like `"01:30:00+02:00"`, `"01:30:00+10:00"` or `"01:30:00Z"`.
Deserialized DateTime that I get for `"01:30:00+10:00"` is `1.01.0001 16:30`, `DateTimeKind` is `Local`. I get this value because my local time is Berlin. Deserializing in other time zone delivers other value.

The problem is that I cannot identify from deserialized `DateTime` `1.01.0001 16:30` that is was originally from time zone UTC+10 and therefore the deserialized local time 16:30 refers to previous day in Berlin.

Example:
If I start deserializing on 8.01.2024 in Berlin then I get `1.01.0001 16:30` for `xs:time` `"01:30:00+10:00"`. But when there (UTC+10) is `8.01.2024 1:30` than it is `7.01.2024 16:30` here (in Berlin).
If I would take deserializing value for current day then I would have `8.01.2024 16:30`. And it would correspond to `8.01.2024 1:30` in time zone UTC+10. It makes error with 1 day difference.

**Comment by mganss** [comment]
Perhaps you can benefit from using `DateTimeOffset` instead of `DateTime` (`-d` option)?

**Comment by bajker-sl** [comment]
Oh, thanks. I have to check it out.

**Comment by mganss** [comment]
I'm closing this for now. Feel free to report here any issues you encounter.
