### ISSUE TITLE
A typo and a request 

### ISSUE THREAD

**Issue by tbebekis** [mganss/XmlSchemaClassGenerator#474]
Hi, thanks for the great job and Happy New Year.

**Typo**
There is a typo in command line options, it's an i in the InitWithoutConstructorInitialization

Currently is InitiWithoutConstructorInitialization.

**Request**
I need to have auto-properties initialized when they are classes or Lists.

Regarding Lists I have tried all --collectionSettersMode possible values and I don't see any difference.

How can achieve the following?

```
public class Address
{
    public string Country { get; set;}
    public string City { get; set;}
    public string Street { get; set;}
    public string PostCode { get; set;}
}

public class Customer
{
    public Address MainAddress { get; set; } = new Address();               // object auto-property initialized
    public List<Address> AddressList { get; set; } = new List<Address>();   // list auto-property initialized
}
```

**Comment by mganss** [comment]
Thanks for reporting the typo. It has been fixed.

For collections, the initialization should take place in the constructor. I don't think auto property initializers are ever generated by XmlSchemaClassGenerator. Can you provide a schema example where collection initialization does not take place?

The other case (Address initialization) I think is currently unsupported.

**Comment by tbebekis** [comment]
ok, thank you
