### ISSUE TITLE
Add sample code of howto use XmlSchemaClassGenerator.Console

### ISSUE THREAD

**Issue by sa-he** [mganss/XmlSchemaClassGenerator#484]
Hi,

could you please add sample code that uses XmlSchemaClassGenerator.Console?

Background:
Currently, I run xscgen in a pre-build event. I wonder if/how it's possible to run it without the need that every developer and compile engine has to install it as "dotnet tool". XmlSchemaClassGenerator.Console looks promising, but I'm just failing to find a way of how to call it during pre-build.

Thanks, Sam

**Comment by mganss** [comment]
You can use xscgen as a [local tool](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool). Once you've set up the tool manifest, the local tool will be installed during the restore phase of the build. To invoke the local tool during the build, use something like this:

```xml
<Target Name="RunXscGen" BeforeTargets="CoreCompile">
    <Exec Command="dotnet tool run xscgen ..." />
</Target>
```

**Comment by sa-he** [comment]
Might it help to add somthing like this to the readme?

Initialize your project for automatic code-generation during build by:

```CMD
cd your\root-dir\src
dotnet new tool-manifest
dotnet tool install dotnet-xscgen
rem this created a new file ".config\dotnet-tools.json", save it in your SCM
```
Once you did that, you can use xscgen during build in your csproj like:

```XML
<Target Name="RunXscGen" BeforeTargets="CoreCompile">
    <Exec Command="dotnet tool restore&#xD;&#xA;dotnet tool run xscgen ..." />
</Target>
```
