### ISSUE TITLE
Change return code on error

### ISSUE THREAD

**Issue by sa-he** [mganss/XmlSchemaClassGenerator#485]
Hi,

if xscgen processes an invalid XSD file, it nicely writes a human readable error message to the console. However, the return code stays 0.

Background:
When embedding the call of xscgen in a batch file or powershell script, the caller might want to know if everything worked well or not. A way to achieve this could be using the return code.

Thanks, Sam

**Comment by mganss** [comment]
Thanks for the suggestion. I've added code to return a nonzero status if a schema is invalid. See here for all possible exit codes:
https://github.com/mganss/XmlSchemaClassGenerator/blob/2369145a38fb1fa91023f4c8c45bfcb787578090/XmlSchemaClassGenerator.Console/Program.cs#L274-L281
