### ISSUE TITLE
Modify the behaviour of "Specified"-properties to include empty not null collections

### ISSUE THREAD

**Issue by Stahhl** [mganss/XmlSchemaClassGenerator#490]
Hello if this is just me failing to RTFM let me know.

Is it possible to modify the generated "Specified"-properties to include empty not null collections in the serialized xml output?

From this:
```c#
[System.Xml.Serialization.XmlIgnoreAttribute()]
public bool FoosSpecified
{
    get
    {
        return ((this.Foos != null)
                    && (this.Foos.Count != 0));
    }
}
```
To this:
```c#
[System.Xml.Serialization.XmlIgnoreAttribute()]
public bool FoosSpecified
{
    get
    {
        return this.Foos != null;
    }
}
```

I want the end result to look like this:
```xml
<Response>
  <Foos />
</Response>
```

**Comment by mganss** [comment]
I've added the `ec` configuration option in 2.1.1107.

**Comment by Stahhl** [comment]
Thanks for the amazingly quick response! 🥇🏆
