### ISSUE TITLE
extension and group mapping

### ISSUE THREAD

**Issue by Falco20019** [mganss/XmlSchemaClassGenerator#5]
It would be nice to be able to map the extension and grouping features from XSD onto the generated classes. I have solved it using inheritance for extension and interfaces for groups. I'm not sure if this works in general but it worked for my usecase.

I needed this feature for mapping the old IS24 XML format to the new one, to fill the properties interface-wise and not copy-paste all the mapping for each class. Would be great to have it in your version if you see it as generalizable.

Here an example of how my generated RealEstates class looks like:
https://raw.githubusercontent.com/Falco20019/IS24RestApi/master/IS24RestApi/generated/IS24RestApi.Offer.RealEstates.cs

I have not published my fork yet since I just hacked the feature quick & dirty into your nice code and since it doesn't merge with your new additions. If you think this could be something interesting, I try to clean it up and create a pull request.

**Comment by mganss** [comment]
That would be huge. I just had that some problem with the Enev2014 properties. Currently I don't see a reason why this shouldn't work for all cases. It would be great if you could make a PR!

**Comment by mganss** [comment]
I can see the benefit from using interfaces for groups, but inheritance support has always been there or am I missing something?

**Comment by Falco20019** [comment]
You are right, inheritance is already there. Just the interface part is missing. I try to look into it today evening, maybe the merge conflicts are not too hard to solve. But too much for yesterday after searching for hours for a problem in the IS24RestApi just to find out that IS24 had a problem on their side...

I close this until then, since the pull request opens a new issue.

**Comment by mganss** [comment]
OT rant: I just checked the IS24 schema again regarding the Enev2014 elements and it seems that although they're using both inheritance and groups they're still duplicating lots of elements all over the place, i.e. they have the same elements in different groups (LivingInformation, ExtendedAssistedLiving, etc.). Also, while they had the chance to structurally enforce invalid combinations (e.g. cannot have electricityConsumption on Apartment types because apartments are obviously always located in residential houses), they chose to check this at runtime.

**Comment by Falco20019** [comment]
:+1: Would have been easier to work with the API if they had chosen to avoid this duplicates. The need of creating a [matrix](http://api.immobilienscout24.de/content/dam/is24/documents/api/Field-overview-energy-certificate.PNG) to let people understand how to use it is just absurd. Like you already said, big structural issue by design...
