### ISSUE TITLE
Class name collisions and loss of schema

### ISSUE THREAD

**Issue by davidruhmann** [mganss/XmlSchemaClassGenerator#50]
Encountered an issue with the class generation using a large set of schema I was given.  Here is a part of the schema that causes this problem:
```xml
<xs:element name="CreateSessionResponse">
	<xs:complexType>
		<xs:sequence>
			<xs:element maxOccurs="1" minOccurs="0" name="CreateSessionResult" type="tns:CreateSessionResponse"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>
<xs:complexType name="CreateSessionResponse">
	<xs:complexContent mixed="false">
		<xs:extension base="tns:OutputResponse">
			<xs:sequence>
				<xs:element maxOccurs="1" minOccurs="0" name="output" type="tns:CreateSessionResult"/>
			</xs:sequence>
		</xs:extension>
	</xs:complexContent>
</xs:complexType>
```
There are two nodes that both get constructed into classes with the same name.

This is what is generated for the above xml.  You can see two XmlTypeAttributes listed; once for each node, but only one class gets actually written out.  Leaving me with an incomplete implementation.
```csharp
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.85.0")]
    [System.Xml.Serialization.XmlTypeAttribute("CreateSessionResponse", Namespace="http://example.com/service/v1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlRootAttribute("CreateSessionResponse", Namespace="http://example.com/service/v1")]
    public partial class CreateSessionResponse : OutputResponse
    {
        
        [System.Xml.Serialization.XmlElementAttribute("output", Namespace="http://example.com/service/v1")]
        public CreateSessionResult output { get; set; }
    }
```

I am unable to change the source schema and do not believe it to be an issue with the schema as it is generated.  Also from having used svcutil on this schema, I know that it will resolve class name collisions by appending incremental numbers to the end of the duplicates.  Personally, I do not like the incremental numbers but it does solve the issue.

What are your thoughts on this?

Here is what svcutil generates for comparison
```csharp
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSessionResponse", WrapperNamespace="http://example.com/service/v1", IsWrapped=true)]
    public partial class CreateSessionResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://example.com/service/v1", Order=0)]
        public ExampleService.CreateSessionResponse CreateSessionResult;

        public CreateSessionResponse1()
        {
        }

        public CreateSessionResponse1(ExampleService.CreateSessionResponse CreateSessionResult)
        {
            this.CreateSessionResult = CreateSessionResult;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://example.com/service/v1")]
    public partial class CreateSessionResponse : OutputResponse
    {

        private CreateSessionResult outputField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CreateSessionResult output
        {
            get
            {
                return this.outputField;
            }
            set
            {
                this.outputField = value;
            }
        }
    }
```

**Comment by mganss** [comment]
Yes, that's indeed a problem. Currently, the qualified name of a type serves as an internal identifier to determine if two types are equal. Thus, in the example, when the element named `CreateSessionResponse` is encountered (elements are processed after types although it's the other way around in the xsd), it is (falsely) determined that a model has already been created for this type: https://github.com/mganss/XmlSchemaClassGenerator/blob/738e3333c5459402341ed9a6badfa12097508b5b/XmlSchemaClassGenerator/Generator.cs#L337
AFAICT at first glance, changing this should be fairly easy given that we already have https://github.com/mganss/XmlSchemaClassGenerator/blob/738e3333c5459402341ed9a6badfa12097508b5b/XmlSchemaClassGenerator/CodeUtilities.cs#L158-L170
It'd be awesome if you could help implement this.

**Comment by bcallaghan-et** [comment]
Has there been any update on this in the past year? I have a similar problem with a third-party schema that I can't change.

```xml
<complexType name="MyType">
  <simpleContent>
    <extension base="string">
      <attribute name="MyAttribute" type="vsi:MyAttributeType" use="optional"/>
    </extension>
  </simpleContent>
</complexType>
<element name="MyType">
  <simpleType>
    <annotation>
      <documentation>CH1 - Choice 1</documentation>
      <documentation>CH2 - Choice 2</documentation>
      <documentation>CH3 - Choice 3</documentation>
    </annotation>
    <restriction base="string">
      <enumeration value="CH1"/>
      <enumeration value="CH2"/>
      <enumeration value="CH3"/>
    </restriction>
  </simpleType>
</element>
```
This generates an enum, but it doesn't generate a class for the complex type. All properties that use the complex type then use the enum and have the wrong data type.

**Comment by mganss** [comment]
No progress, unfortunately.
