### ISSUE TITLE
Interface definitions are duplicated

### ISSUE THREAD

**Issue by dtila** [mganss/XmlSchemaClassGenerator#501]
Hi,

I am using the following XSD schemas: https://op.europa.eu/documents/3938058/6560998/TED_publication_R2.0.9.S01.E01_019-20160603.zip/647c626b-72e7-9fe9-2561-87074fe0b327

When I execute  
`xscgen -n Test .\TED_EXPORT.xsd `
I get the following error in the compiler:

![image](https://github.com/mganss/XmlSchemaClassGenerator/assets/5718468/9220ef7e-3791-45da-b6a6-78f733126e4e)

Trying to figure it out the issue, it seems when interface generation is enabled, a member with the same name has 2 types:

**interface definition:**

```
      [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("(19|20).{8}")]
      System.Collections.ObjectModel.Collection<System.DateTime> DateEnd
      {
          get;
      }
```

**class definition (that implements the interface)**

`        public System.DateTime DateEnd { get; set; }`

If interface generation is disabled, the code is generated successfully. 
I suspect there could be a bug either in XSD or in the tool.

Regards,

**Comment by mganss** [comment]
This is similar to #475. A similar issue also arises with nullable vs non-nullable types that are not aligned between the interface definition and implementing classes. I've introduced a hacky fix for both issues by forcibly aligning the interface and class definitions.
