### ISSUE TITLE
Option -a|--pascal not possible to set to false

### ISSUE THREAD

**Issue by nickee10** [mganss/XmlSchemaClassGenerator#502]
Found out that you can't reset the option for PascalNaming when you put in the option `-a|--pascal` due to it having true as default. There is no way to set it to false with current implementation.

Ought to be like  ` { "a|pascal", "use Pascal case for class and property names (default is enabled)", v => pascal = v == null || bool.TryParse(v, out var psc) && psc },`
Instead of  ` { "a|pascal", "use Pascal case for class and property names (default is enabled)", v => pascal = v != null},`

**Comment by mganss** [comment]
Try `-a-`

**Comment by nickee10** [comment]
Thanks, not so obvious but it helped
