### ISSUE TITLE
I generate a new file .cs, each uint is replaced by int

### ISSUE THREAD

**Issue by egiorgioPatagonian** [mganss/XmlSchemaClassGenerator#512]
Hi there.
I would like that when I generate a new file .cs, each uint is replaced by int.
Is there any option to do that?
"xscgen [OPTIONS]" 

example 
public **uint** SpotLength { get; set; } ->  public **int** SpotLength { get; set; } 

	<xsd:simpleType name="SpotLengthType">
		<xsd:annotation>
			<xsd:documentation>Duration of spot in seconds from 1s to 23h:59m:59s.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:maxInclusive value="86399"/>
			<xsd:minInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>

**Comment by mganss** [comment]
Yes, use the `-i` option. For this use case, `-ii` should work.
