### ISSUE TITLE
Emit XmlArrayAttribute in (probably) non-standard XSD

### ISSUE THREAD

**Issue by Dialecticus** [mganss/XmlSchemaClassGenerator#515]
Suppose we have this schema, example.xsd:

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="example.com" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="example.com">
<xs:element name="Example" type="tns:Example" />

<xs:complexType name="Example">
	<xs:sequence>
		<xs:element name="exampleString" type="xs:string" />
		<xs:element minOccurs="0" maxOccurs="unbounded" name="exampleThings" type="tns:Thing" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="Thing">
	<xs:sequence>
		<xs:element name="thingString" type="xs:string" />
	</xs:sequence>
</xs:complexType>
</xs:schema>

```

Both xsd.exe and xscgen will attach `XmlElementAttribute` to `exampleThings` property. But I need `XmlArrayAttribute` there, or no attribute at all. Is it possible to make it so, even if the schema is not up to standard? Not sure if important, but this is the command line:

    xsdgen example.xsd -a- --ct=System.Array --csm=Public -cc- -c -n:example.com

**Comment by Dialecticus** [comment]
Actually, strike the above. I don't really need the XmlArrayAttribute, but that my wsdl looks nice. I use the autogenerated code in my web service, and the code would create a lot of "ArrayOf" xsd elements. When I removed the option `--ct=System.Array` all the unnecessary ArrayOf elements went away. Another issue came up, which looks like a bug, but I will create a separate github issue for that.

**Comment by mganss** [comment]
Is this resolved?

**Comment by Dialecticus** [comment]
I think it is. According to [Microsoft](http://msdn.microsoft.com/en-us/library/2baksw0z.aspx) xscgen is doing its job. `XmlElement` should be used in this case. `SoapCore` library is apparently the cause of all my woes this week, and the reason for both my reports here.
