### ISSUE TITLE
Add option to use "Legacy" pascal case naming

### ISSUE THREAD

**Issue by Pretasoc** [mganss/XmlSchemaClassGenerator#520]
As the old saying goes 'Every change breaks someones workflow'. This time it hit me.

I have an externally supplied xsd file which contains underscores in element names. I used to generate the classes with `2.0.732`. In that version the generated classes would contain underscores as well (`<element name="foo_bar" />` became `class Foo_Bar`). When i now tried to update to to the changes in  46b2dc3a0370f4042940cdce7fcffa0519039930 underscores are now removed from identifiers.

Carring that change forward in my project is not an option as is would affect some downstream applications, that rely on that generated type names. For now i will stay on the old version, but it would be great to have an upgrade path available.

**Comment by mganss** [comment]
Oh crap, I'm sorry 😳 Do you think you could get by with a type name mapping file (`--tnsf` option)?

**Comment by Pretasoc** [comment]
I'll take a look at it. Im not sure how easy it will be to generate the mapping file. But i guess it should be possible with an xslt script.

**Comment by mganss** [comment]
I've added an option to use the legacy naming scheme (`--namingScheme=Legacy`).
