### ISSUE TITLE
No code generated for schemas located with https: and locally, but http: works.

### ISSUE THREAD

**Issue by phoyd** [mganss/XmlSchemaClassGenerator#534]
I believed that

`XmlSchemaClassGenerator.Console.exe --verbose --output=gen "https://schemas.opengis.net/gml/3.2.1/gml.xsd"`

should generate classes for the opengis gml schema types in the exsisting folder "gen". However what happens is 

1) gen stays empty
2) I get a lot of messages about types already been declared: 

```
[...]
The complexType 'http://www.opengis.net/gml/3.2:FeatureArrayPropertyType' has already been declared.
The complexType 'http://www.opengis.net/gml/3.2:BoundedFeatureType' has already been declared.
The complexType 'http://www.opengis.net/gml/3.2:AbstractFeatureCollectionType' has already been declared.
The complexType 'http://www.opengis.net/gml/3.2:FeatureCollectionType' has already been declared.
The complexType 'http://www.opengis.net/gml/3.2:IndirectEntryType' has already been declared.
The complexType 'http://www.opengis.net/gml/3.2:DefinitionProxyType' has already been declared.
The simpleType 'http://www.opengis.net/gml/3.2:IncrementOrder' has already been declared.
The complexType 'http://www.opengis.net/gml/3.2:MovingObjectStatusType' has already been declared.
```

Next I mirrored the schema and tried the local files: 

`XmlSchemaClassGenerator.Console.exe -o "out" -v schemas.opengis.net/gml/3.2.1/gml.xsd`

And got the same messages as above and no code. 

### **HOWEVER**

If I use **http:** instead of **https:** to locate the schema: 

`XmlSchemaClassGenerator.Console.exe --verbose --output=gen "https://schemas.opengis.net/gml/3.2.1/gml.xsd"`

The classes are generated, and they compile and work. 

I've tried: 
* The current xscgen tool in windows and linux
* The current 2.1.1167 release on windows and linux
* A build of HEAD on linux.

What is wrong? Did I miss something? The gml schemas do a lot of mutual XIncludes, which might explain why the tools receives duplicate definition -  so I'd guess that some check for recursive XIncludes is kind of broken?

**Comment by mganss** [comment]
There is a chain of includes that leads to http://schemas.opengis.net/iso/19139/20070417/gco/basicTypes.xsd which has

```xsd
<xs:import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
```

The validation in `XmlSchemaSet` treats this as a different URI than https://schemas.opengis.net/gml/3.2.1/gml.xsd.

**Comment by phoyd** [comment]
Oh wow, thank you! I fixed this for me by using a custom XmlResolver that forces an URL scheme.
