### ISSUE TITLE
Unhandled Exception: System.Xml.Schema.XmlSchemaException: The global element has already been declared.

### ISSUE THREAD

**Issue by MarkoKacprzak** [mganss/XmlSchemaClassGenerator#54]
Folder aa contains A.xsd, B.xsd, C.xsd and D.xsd like in examples: 
http://www.xfront.com/Dealing-With-Multiple-XML-Schema-Files.pdf

Executing:
XmlSchemaClassGenerator.Console.exe -p test aa\\*.xsd

generate error:
Unhandled Exception: System.Xml.Schema.XmlSchemaException: The global element 'B' has already been declared.
   at System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.BaseProcessor.AddToTable(XmlSchemaObjectTable table, XmlQualifiedName qname, XmlSchemaObject item)
   at System.Xml.Schema.Compiler.Prepare(XmlSchema schema, Boolean cleanup)
   at System.Xml.Schema.XmlSchemaSet.Compile()
   at XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)

[aa.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/1864693/aa.zip)

**Comment by mganss** [comment]
It works when you give only the "leaf" schema on the commandline, i.e.

```
XmlSchemaClassGenerator.Console.exe -p test aa\A.xsd
```

**Comment by MarkoKacprzak** [comment]
Yes but i've found several times that bug - and i want to use always *.xsd in console - so probably it is a better solution than telling developers to not match all xsd. I have more example with that error - but i don't find any problems with checking new one with your and my company samples. It is very nice feature to load all xsd from specific folder for example XsdTypes/*/*.xsd


________________________________
Od: Michael Ganss <notifications@github.com>
Wysłane: 3 kwietnia 2018 13:04
Do: mganss/XmlSchemaClassGenerator
DW: Marek Kacprzak; Author
Temat: Re: [mganss/XmlSchemaClassGenerator] Unhandled Exception: System.Xml.Schema.XmlSchemaException: The global element has already been declared. (#54)


It works when you give only the "leaf" schema on the commandline, i.e.

XmlSchemaClassGenerator.Console.exe -p test aa\A.xsd

**Comment by mganss** [comment]
Fixed by #55
