### ISSUE TITLE
Ship as a DotNetCliTool

### ISSUE THREAD

**Issue by kasper3** [mganss/XmlSchemaClassGenerator#56]
With SDK based projects, we can use `DotNetCliToolReference`. Some tools are available https://github.com/dotnet/corefx/issues/25138 and a bunch of them are being shipped from https://github.com/aspnet/DotNetTools.

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility

**Comment by mganss** [comment]
Sorry, I only tested locally using the package that was built from the XmlSchemaClassGenerator.Console project. Though the dotnet-xscgen binary gets included in the XmlSchemaClassGenerator NuGet package in the tools folder, it isn't found when trying to execute dotnet xscgen 🙄 

From the documentation it's not clear to me how we can include the tool binary in the library NuGet package.

**Comment by mganss** [comment]
I've released a separate NuGet package [dotnet-xscgen](https://www.nuget.org/packages/dotnet-xscgen).

**Comment by kasper3** [comment]
Example:

Using dotnet cli 2.1 (download and extract https://dotnetcli.azureedge.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.zip in dotnet21 directory for exmaple)

```cmd
dotnet21\dotnet.exe tool install dotnet-watch ^
    --version 2.1.0-*  --tool-path MyDir  ^
    --source-feed https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json 
```

this installs a tool called `dotnet-watch` (.exe)  (hosted in aspnet's myget feed) in `MyDir` directory at current working directory.

**Comment by kasper3** [comment]
We can also install it globally using:

```
dotnet21\dotnet.exe tool install dotnet-watch ^
    --version 2.1.0-*  --global ^
    --source-feed https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json 
```

**Comment by mganss** [comment]
It's working for me now using the dotnet-xscgen NuGet package.

**Comment by kasper3** [comment]
Great! Ah, but we cannot install it as standalone (dotnet-tool install command):

```
donet21\dotnet.exe tool install dotnet-xscgen --tool-path Tools --version 2.0.102
```

> error NU1212: Invalid project-package combination for dotnet-xscgen 2.0.102. DotnetToolReference project style can only contain references of the DotnetTool type
> The tool package could not be restored.
> Tool 'dotnet-xscgen' failed to install.

Please see @dasMulli's comment at https://github.com/dotnet/cli/issues/9060#issuecomment-380778476. We can just add:

```xml
<PropertyGroup>
  <PackAsTool>true</PackAsTool>
  <ToolCommandName>dotnet-xscgen</ToolCommandName>
</PropertyGroup>
```

in https://github.com/mganss/XmlSchemaClassGenerator/blob/7e1889fb10bbb65ea495409ae776050e502559e2/XmlSchemaClassGenerator.Console/XmlSchemaClassGenerator.Console.csproj then publishing the package would publish tool as well.

Found various examples: https://github.com/search?utf8=q=Microsoft.NET.SDK+ToolCommandName&type=Code

**Comment by dasMulli** [comment]
fyi: Not sure how good docs are, but there are two blog posts:
https://www.natemcmaster.com/blog/2018/02/02/dotnet-global-tool/
https://dasmulli.blog

**Comment by kasper3** [comment]
Thanks Martin! I think it is known to docs team that there are discrepancies in tools docs: https://github.com/dotnet/docs/pull/4911#pullrequestreview-111042492. Maybe we can contribute there to improve the text and examples from the developers' perspective.

Circling back to example in your blog: ` <ToolCommandName>sayhi</ToolCommandName>`, could you please suggest whether we should use `<ToolCommandName>xscgen</ToolCommandName>` here or `<ToolCommandName>dotnet-xscgen</ToolCommandName>`? (is `dotnet-` prefix before `<toolname>` implied?)

**Comment by mganss** [comment]
Added `PackAsTool` and `ToolCommandName`. Still not working for me, tho 😞

**Comment by dasMulli** [comment]
The `ToolCommandName` specifies the executable name that will be installed. so if it is `foo` you can run `$ foo --some-arg` everywhere, if it is `dotnet-foo`, you can run `$ dotnet-foo --some-args` but also make the `dotnet` cli command forward to it ba calling `$ dotnet foo --some-args` (looks for a `dotnet-foo` in the $PATH)

**Comment by mganss** [comment]
@kasper3 Can you verify that it's working now with .NET Core 2.1?

**Comment by kasper3** [comment]
@mganss, it is still the old one 2.0.105 on nuget? https://www.nuget.org/packages/dotnet-xscgen

**Comment by mganss** [comment]
Yes, I meant with a local build.

**Comment by kasper3** [comment]
@mganss, it works with local package build:

```cmd
cd c:\projects
git clone https://github.com/mganss/XmlSchemaClassGenerator
cd XmlSchemaClassGenerator\
dotnet21.exe restore
dotnet21.exe pack -c release /p:VERSION=2.3.3
cd c:\some\where\else
dotnet21.exe tool install dotnet-xscgen --tool-path MyDir --version 2.3.3 
    --source-feed C:\projects\XmlSchemaClassGenerator\XmlSchemaClassGenerator.Console\bin\Release


MyDir\dotnet-xscgen --help
```

**Comment by kasper3** [comment]
@mganss, could you please push a new version release to nuget? :)

**Comment by mganss** [comment]
@kasper3 You mean built with .NET Core 2.1? Does that work with AppVeyor?

**Comment by kasper3** [comment]
@mganss,

```diff
- image: Visual Studio 2017
+ image: Visual Studio 2017 Preview
```

in appveyor.yml. they have just updated it https://github.com/appveyor/ci/issues/2120#issuecomment-381175687 and I have just confirmed it 😄

**Comment by mganss** [comment]
Done: https://www.nuget.org/packages/dotnet-xscgen/2.0.106

**Comment by kasper3** [comment]
Great! `dotnet.exe tool install dotnet-xscgen --tool-path Tools` worked!
There are some details how to use it with older version etc. https://github.com/dotnet/cli/issues/9060#issuecomment-381179998, but that will be improved once 2.1 is out. Current we can use it with 2.0 as you mentioned above (https://github.com/mganss/XmlSchemaClassGenerator/issues/56#issuecomment-380773591).

Thank you!
