### ISSUE TITLE
How do you disable flag attributes (e.g. pascal case) in command line?

### ISSUE THREAD

**Issue by zaus** [mganss/XmlSchemaClassGenerator#59]
https://github.com/mganss/XmlSchemaClassGenerator/blob/b77caa93d57e0242d5ee93d864de296442af77df/XmlSchemaClassGenerator.Console/Program.cs#L74

`v` is never null if you're providing the argument via command line.

* given `--pascal` you get the argument name: "pascal"
* given `--pascal=` you also get the argument name: "pascal"

Maybe instead:
````
v => pascal = v != nameof(pascal)
````

**Comment by zaus** [comment]
Could use a regex to replace all the 'null flags' with `nameof`:

````
([^\s]*) = v != null    -->    $1 = v != nameof($1)
````

**Comment by mganss** [comment]
Use `-a-` or `--pascal-`. [Mono.Options](https://components.xamarin.com/gettingstarted/mono.options?version=5.3.0) is used for command line parsing.

**Comment by zaus** [comment]
Well I just learned something very important about Mono.Options (and similarly, [NDesk.Options](http://www.ndesk.org/Options)), thank you.
