### ISSUE TITLE
Add API to supply XmlSchemaSet directly rather than just files

### ISSUE THREAD

**Issue by twsouthwick** [mganss/XmlSchemaClassGenerator#63]
I'm having trouble with a multifile schema when passing it files as the XmlResolver isn't set correctly on the schema set. I'd prefer to just load up my schemas myself to ensure everything is resolved correctly. I took a look at the way this is set up and it would be difficult as-is as the XmlSchemaSet is a read only item that is just added to (this design also makes reuse of the generator difficult, but that's probably a different issue).

My suggestion would be to add a configuration item that was a "SchemaProvider":

```csharp
public interface ISchemaSetProvider
{
  XmlSchemaSet GetSchemaSet(GeneratorConfiguration config);
}
```

with the default implementation loading the schemas as is currently done.

**Comment by mganss** [comment]
Great idea. If you could provide a PR to implement this, that'd be 💯. Same for #64 .

**Comment by twsouthwick** [comment]
Sure - I'd be happy to create a PR. As I've looked in the code, I'm wondering why you have the Generator proxy properties between the GeneratorConfiguration - do I need to add the property in both places?

**Comment by mganss** [comment]
I believe it's for historical reasons. No need to add it in both places.
