### ISSUE TITLE
Expose NuGet packages from AppVeyor build

### ISSUE THREAD

**Issue by twsouthwick** [mganss/XmlSchemaClassGenerator#68]
Would it be possible to get a NuGet feed from the AppVeyor build? It looks like they are uploaded as artifacts.

**Comment by mganss** [comment]
Sure, do you know how this works? AFAICT, artifacts should be automatically pushed to the project feed. In [the docs](https://www.appveyor.com/docs/nuget/) it says:
 > The project feed contains all build artifact packages of type “NuGet package”.

The NuGet package files show up fine on [the artifacts page](https://ci.appveyor.com/project/mganss/xmlschemaclassgenerator/build/artifacts) with the correct type of "NuGet package".

**Comment by twsouthwick** [comment]
Yeah, so the artifacts are probably there. You just need to grab the URL of the feed from the appveyor settings and publish that so we can use it (you can customize it too).

**Comment by mganss** [comment]
https://ci.appveyor.com/nuget/xmlschemaclassgenerator-0f1t3r6ti475
No packages 🙁

**Comment by twsouthwick** [comment]
They're there :) You have to view it from something that can list the packages, such as VS, .NET CLI, or NuGet Package Explorer. The link itself is kind of an entry point to a NuGet service

**Comment by mganss** [comment]
Ah ok, I get it. There's the `href` attribute which points to https://ci.appveyor.com/nuget/xmlschemaclassgenerator-0f1t3r6ti475/Packages
