### ISSUE TITLE
XSD is Valid but dotnet-xscgen.exe throws Unhandled exception. System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.

### ISSUE THREAD

**Issue by TonyHenrique** [mganss/XmlSchemaClassGenerator#72]
Some time ago I used XSD.exe

`xsd.exe nfe_v4.00.xsd xmldsig-core-schema_v1.01.xsd /c /edb`

Now I am trying to use XmlSchemaClassGenerator,
Using this XSDs
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=xLaRDcJryNA=

I run:

`dotnet-xscgen.exe nfe_v4.00.xsd xmldsig-core-schema_v1.01.xsd`

Then this Exception occurs:

```
Unhandled exception: System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   em System.Xml.XmlTextReaderImpl.Throw(Exception e)
   em System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   em System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   em System.Xml.Schema.Parser.StartParsing(XmlReader reader, String targetNamespace)
   em System.Xml.Schema.XmlSchema.Read(XmlReader reader, ValidationEventHandler validationEventHandler)
   em XmlSchemaClassGenerator.Generator.<>c__DisplayClass82_0.<Generate>b__0(String f)
   em System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   em XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files)
   em XmlSchemaClassGenerator.Console.Program.Main(String[] args)
```

Can you give a try, using the XSDs provided on the link above?

**Comment by mganss** [comment]
Calling with these arguments works for me:

`nfe_v4.00.xsd leiauteNFe_v4.00.xsd tiposBasico_v4.00.xsd xmldsig-core-schema_v1.01.xsd -n "http://www.w3.org/2000/09/xmldsig#=XmlDSig" -o .`

**Comment by mganss** [comment]
Closing this for now. Feel free to reopen if the issue persists.
