### ISSUE TITLE
Exception: 'http://www.w3.org/2001/XMLSchema:sequence' element is not supported in this context.

### ISSUE THREAD

**Issue by ravensorb** [mganss/XmlSchemaClassGenerator#77]
I am looking to generate a set of classes off of the following XSD file 
http://www.zillow.com/static/xsd/ZillowTypes.xsd

and I am running in to the following exception below

```
Unhandled Exception: System.Xml.Schema.XmlSchemaException: The 'http://www.w3.org/2001/XMLSchema:sequence' element is not supported in this context.
   at System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.XmlSchemaSet.ParseSchema(String targetNamespace, XmlReader reader)
   at System.Xml.Schema.XmlSchemaSet.Add(String targetNamespace, String schemaUri)
   at XmlSchemaClassGenerator.Generator.Generate(IEnumerable`1 files)
   at XmlSchemaClassGenerator.Console.Program.Main(String[] args)
```

Any thoughts?

**Comment by mganss** [comment]
The schema is invalid at line 852:

```xml
<xsd:element name="buying" minOccurs="0" maxOccurs="unbounded">
    <xsd:sequence>
    ...
    </xsd:sequence>
</xsd:element>
```
Exception message:
> The element 'element' in namespace 'http://www.w3.org/2001/XMLSchema' has invalid child element 'sequence' in namespace 'http://www.w3.org/2001/XMLSchema'. List of possible elements expected: 'annotation, simpleType, complexType, unique, key, keyref' in namespace 'http://www.w3.org/2001/XMLSchema'.

It works if you modify the xsd by wrapping the inner sequence in a complexType.

[Here's](https://stackoverflow.com/questions/13239726/zillows-searchresults-xsd-and-visual-studios-xsd-command) a StackOverflow question from 2012 where this problem has already been discussed. So obviously this hasn't been fixed for more than 5 years 🙄

**Comment by ravensorb** [comment]
Interesting. Is there any way to "infer" what is wrong and correct for it within the tool?

**Comment by mganss** [comment]
No. If the schema is invalid, it can't be parsed. XML is not meant to be parsed in a ["lenient" way](https://en.wikipedia.org/wiki/Tag_soup#XML_and_XHTML).

**Comment by ravensorb** [comment]
Fair enough.
