### ISSUE TITLE
Incorrect property type in generated class

### ISSUE THREAD

**Issue by andrewkip** [mganss/XmlSchemaClassGenerator#80]
Hello, in generated classes [mdlp.zip](https://github.com/mganss/XmlSchemaClassGenerator/files/2361568/mdlp.zip) by the schemas in attached files (XmlSchemaClassGenerator.Console.exe documents.xsd -p=mdlp)
[XSD.ZIP](https://github.com/mganss/XmlSchemaClassGenerator/files/2361557/XSD.ZIP)
for class Register_End_Packing wrong type for property  Signs is: 

System.Collections.ObjectModel.Collection<string>, but should not it be Register_End_PackingSigns?

**Comment by mganss** [comment]
This is an "optimization" because the inner complex type contains just a collection of strings. The extra unused class is output anyway, though (see #32).

**Comment by andrewkip** [comment]
Ok I see.

I've checked data serialized/deserialized ok. 

Thank you.
