### ISSUE TITLE
More granular control over integer-derived types

### ISSUE THREAD

**Issue by girtsl** [mganss/XmlSchemaClassGenerator#89]
I have been handed an XSD in which the authors have defined a few custom simple types using partially bounded integers:
```
<xsd:simpleType name="Nonnegativeinteger10">
	<xsd:restriction base="xsd:nonNegativeInteger">
		<xsd:totalDigits value="10"/>
	</xsd:restriction>
</xsd:simpleType>
<xsd:simpleType name="Nonnegativeinteger3">
	<xsd:restriction base="xsd:nonNegativeInteger">
		<xsd:totalDigits value="3"/>
	</xsd:restriction>
</xsd:simpleType>
```
In the generated C# classes these properties by default have the type `string` whereas I expected numeric types. It's possible to take the risk and map all integer-derived types to e.g. `long` with `--integer=long` which gives a much better result but I feel like it's too broad of a scope.

Would it be possible to define a more fine-grained map for the partially bounded integer types, depending on the `totalDigits` facet? Something like:

| XSD type | totalDigits | C# type|
|-----------|-------------|---------|
| positive and non-negative| <3 | byte |
| positive and non-negative| <5 | ushort |
| positive and non-negative| <10 | uint |
| positive and non-negative| <20 | ulong |
| positive and non-negative| <30 | decimal |
| positive and non-negative| >=30 | string (or consumer-defined type) |
| non-positive and negative| <3 | sbyte |
| non-positive and negative| <5 | short |
| non-positive and negative| <10 | int |
| non-positive and negative| <19 | long |
| non-positive and negative| <29 | decimal |
| non-positive and negative| >=29 | string (or consumer-defined type) |

Granted, it will still be possible to set invalid values, but the C# types would be much closer to the XSD restrictions.

Alternatively, would it be possible to add a way to pass a custom map in which I could specify the desired mapping: `Nonnegativeinteger10` -> `ulong`, `Nonnegativeinteger3` -> `ushort`? This approach might even be more desired as it would allow more flexibility with custom types.

**Comment by mganss** [comment]
These are both good ideas. Could you come up with a PR?

The relevant code is here https://github.com/mganss/XmlSchemaClassGenerator/blob/72abaaf2f6a4ceef05b5aeb94194283a83cc4230/XmlSchemaClassGenerator/TypeModel.cs#L1188-L1194 and here https://github.com/mganss/XmlSchemaClassGenerator/blob/72abaaf2f6a4ceef05b5aeb94194283a83cc4230/XmlSchemaClassGenerator/CodeUtilities.cs#L79-L122

We'll have to make sure that XmlSerializer can handle all of these mappings.
