### ISSUE TITLE
list of enums doesn't convert correctly

### ISSUE THREAD

**Issue by Spongman** [mganss/XmlSchemaClassGenerator#92]
this XSD isn't converting correctly.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://me.me" xmlns:my="http://me.me" elementFormDefault="unqualified">

	<xs:simpleType name="enumType">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="1" />
			<xs:enumeration value="2" />
			<xs:enumeration value="3" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="enumTypeList">
		<xs:restriction>
			<xs:simpleType>
				<xs:list itemType="my:enumType" />
			</xs:simpleType>
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="myClass">
		<xs:sequence>
			<xs:element name="enumType" type="my:enumTypeList" minOccurs="0" />
		</xs:sequence>
	</xs:complexType>

</xs:schema>
```

I'd expect the resulting `MyClass.EnumType` field to have the type `Collection<EnumType>`, but instead it has the type `long?`. can anyone tell me why?

**Comment by mganss** [comment]
`XmlSerializer` [doesn't support](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/t84dzyst(v%3dvs.100)) `xs:list` for elements, only for attributes.

But that's not the reason xscgen doesn't generate correct code here. We simply don't support xs:list very well. What we should do is generate a `string` property for elements and a collection of the list's item type for attributes. Icing on the cake would be to generate an additional adapter property for elements that does string splitting, parsing, and joining.

I hope I can do this in the next few days.

**Comment by Spongman** [comment]
here's a simpler example that doesn't work:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://me.me" xmlns:my="http://me.me" elementFormDefault="unqualified">

	<xs:simpleType name="enumType">
		<xs:restriction base="xs:integer">
			<xs:enumeration value="1" />
			<xs:enumeration value="2" />
			<xs:enumeration value="3" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="myClass">
		<xs:sequence>
			<xs:element name="myEnumTypes">
				<xs:simpleType>
					<xs:list itemType="my:enumType" />
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

```

**Comment by mganss** [comment]
I have made the generated code compatible with XmlSerializer but have not yet implemented the adapter approach. I noticed these issues:

1. The reason XmlSerializer does not support collections for xs:list on elements is that in a sequence with maxOccurs > 1 there can be more than one element, i.e. you'd have to have a collection of collections.
2. XmlSerializer ignores the [DataType property](https://docs.microsoft.com/en-us/dotnet/api/system.xml.serialization.xmlattributeattribute.datatype) for attributes, i.e you can't use a collection for xs:list in these cases, either. This is only relevant where the schema type is ambiguous compared to the .NET type. AFAICT this is only the case for xs:time, xs:date, and xs:datetime (which all map to DateTime) and xs:base64Binary and xs:hexBinary (map to bin[]).
3. Bizarrely, the binary types seemed to have worked, but only if you had previously deserialized in the correct format (see properties base64ListAttr and hexListAttr in the TestList test case). XmlSerializer seems to keep a static mapping of datatypes it has deserialized from and then serializes the corresponding properties in the correct format. This does not work if you're only serializing an object.

I'll try to come up with an adapter approach soon. Ideas and/or PRs welcome 😉
