### ISSUE TITLE
error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

### ISSUE THREAD

**Issue by broersa** [mganss/XmlSchemaClassGenerator#94]
When I generate code from an XSD I get the above compile error. By removing the 'm' from '0m' the line   [System.ComponentModel.DefaultValueAttribute(0m)] the code compiles.

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private decimal _penalty = 0m;
        
        /// <summary>
        /// <para>Optional (default zero) penalty due a non-zero PowerDeficiency.</para>
        /// <para xml:lang="en">Total number of digits in fraction: 4.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute(0m)]
        [System.ComponentModel.DescriptionAttribute("Optional (default zero) penalty due a non-zero PowerDeficiency.")]
        [System.Xml.Serialization.XmlAttributeAttribute("Penalty", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Penalty
        {
            get
            {
                return this._penalty;
            }
            set
            {
                this._penalty = value;
            }
        }

**Comment by mganss** [comment]
Whoa, I didn't know `decimal` is not a primitive type. [Here](https://github.com/dotnet/csharplang/blob/master/spec/attributes.md#attribute-parameter-types) are the rules for attribute parameter types.

Although dropping the `m` from the value makes the code compile, it doesn't work as expected. For example, you'll get an error in Visual Studio when trying to reset a property to its default value from the Properties window.

The only possible way seems to be this:

```C#
[DefaultValue(typeof(decimal), "0")]
public decimal Penalty { get; set; }
```

I also fixed another issue we had with default values for `DateTime`s 🙄
