### ISSUE TITLE
Is it possible to change the visibillity of the generated classes

### ISSUE THREAD

**Issue by LokiMidgard** [mganss/XmlSchemaClassGenerator#95]
Currently When I Use `xscgen.exe` classes are generated as `public` classes. I would preferer them to be `internal` is there a setting to achieve this?

**Comment by mganss** [comment]
No, this is currently not possible but should be very easy to add by setting the `TypeAttributes` of the `classDeclaration` to `NotPublic` [here](https://github.com/mganss/XmlSchemaClassGenerator/blob/0126fc18691baad91b2bb9954c43944bc502ada4/XmlSchemaClassGenerator/TypeModel.cs#L274). Can you provide a PR?

**Comment by LokiMidgard** [comment]
Thanks to the code link you provided, I was able to create pull request #96.
