### ISSUE TITLE
System.Xml.Schema.XmlSchemaException: Element 'http://www.w3.org/2000/09/xmldsig#:Signature' was not declared.

### ISSUE THREAD

**Issue by TonyHenrique** [mganss/XmlSchemaClassGenerator#98]
I am trying to generate C# classes for the **evtAdmissao.xsd**
from this
https://portal.esocial.gov.br/manuais/2019-01-18_esquemas_xsd_v02-05-00.zip

Can you point me to the right command line to generate these classes?

I tried:
```
C:\temp\eSocial\Esquemas XSD v02.05.00>C:\temp\NFe4\XmlSchemaClassGenerator.2.0.197\XmlSchemaClassGenerator.Console.exe evtAdmissao.xsd -n "|xmldsig-core-schema.xsd=http://www.w3.org/2000/09/xmldsig#" -e -c -o eSocial

Exceção Sem Tratamento: System.Xml.Schema.XmlSchemaException: Elemento 'http://www.w3.org/2000/09/xmldsig#:Signature' não foi declarado.
   em System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   em System.Xml.Schema.Compiler.CompileElement(XmlSchemaElement xe)
   em System.Xml.Schema.Compiler.CompileParticleElements(XmlSchemaComplexType complexType, XmlSchemaParticle particle)
   em System.Xml.Schema.Compiler.CompileParticleElements(XmlSchemaComplexType complexType, XmlSchemaParticle particle)
   em System.Xml.Schema.Compiler.CompileComplexTypeElements(XmlSchemaComplexType complexType)
   em System.Xml.Schema.Compiler.Compile()
   em System.Xml.Schema.Compiler.Execute(XmlSchemaSet schemaSet, SchemaInfo schemaCompiledInfo)
   em System.Xml.Schema.XmlSchemaSet.Compile()
   em XmlSchemaClassGenerator.Generator.Generate(XmlSchemaSet set)
   em XmlSchemaClassGenerator.Console.Program.Main(String[] args)

```

**Comment by TonyHenrique** [comment]
Is this some bug, or am I missing something on the command line?

Can you point me to the right command line to generate these classes?

**Comment by mganss** [comment]
You need to also specify the xsd at http://www.w3.org/2000/09/xmldsig. Simply save it to the folder where your other xsd files are located, then specify it on the command line, e.g.

```
xscgen *.xsd -n http://www.w3.org/2000/09/xmldsig#=Dsig
```

Unfortunately, even with the `xmldsig-core-schema.xsd` it did there was a bug before 2.0.199 which probably originated from the fix for #54. I hope I have fixed this now once and for all 🤞

**Comment by TonyHenrique** [comment]
I downloaded the XSD at [http://www.w3.org/2000/09/xmldsig](http://www.w3.org/2000/09/xmldsig), saved as **xmldsig-core-schema.xsd** on the same folder, then run

and got this:

```
Unhandled Exception: System.ArgumentException: Item with Same Key has already been added.
   em System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   em System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   em XmlSchemaClassGenerator.EnumerableExtensions.ToNamespaceProvider(IEnumerable`1 items, GenerateNamespaceDelegate generate)
   em XmlSchemaClassGenerator.Console.Program.Main(String[] args)

```
Can you please download this 
https://portal.esocial.gov.br/manuais/2019-01-18_esquemas_xsd_v02-05-00.zip
and check if it works on your machine/version?
For example try to generate the classes for the **evtAdmissao.xsd** file.

**Comment by mganss** [comment]
It works for me using these command line arguments. Please make sure you are using 2.0.199 (released today).

**Comment by TonyHenrique** [comment]
Thanks, It works with version 2.0.199 for the eSocial XSD files.

But I also tried to use with another XSD files from NFe Project as mentioned in https://github.com/mganss/XmlSchemaClassGenerator/issues/72

`C:\temp\NFe4\XmlSchemaClassGenerator.2.0.199\XmlSchemaClassGenerator.Console.exe *nfe_v4.00.xsd leiauteNFe_v4.00.xsd tiposBasico_v4.00.xsd xmldsig-core-schema_v1.01.xsd -n "http://www.w3.org/2000/09/xmldsig#=XmlDSig" -o NFe4`

I also tried:

`C:\temp\NFe4\XmlSchemaClassGenerator.2.0.199\XmlSchemaClassGenerator.Console.exe *.xsd -n "http://www.w3.org/2000/09/xmldsig#=Dsig" -e -c -o NFe4`

No errors appear in the Console. But this time there is no output in the folder. It creates the folder, but it is empty.
